# Caller: gen_vnpt.py — from cards_part2 import CARDS as C2
# Glob: no prior cards_part2.py. Synthetic interview cards; no dates.
# User: Create a complete offline HTML study page at interview-cheatsheet/vnpt-devops.html

def I(sec, title, sub, q_en, a_en, q_vi, a_vi, star=""):
    return {
        "sec": sec, "kind": "interview", "title": title, "sub": sub,
        "q_en": q_en, "a_en": a_en, "q_vi": q_vi, "a_vi": a_vi, "star": star,
    }


CARDS = [
    I("sec-fit", "Tell me about yourself (DevOps)", "60–90s spoken intro",
      "Tell me about yourself.",
      "I'm a DevOps engineer with strong hands-on experience across the delivery loop: Git-based collaboration, CI/CD with Jenkins/GitLab-style pipelines, containerizing apps with Docker, operating Kubernetes workloads, and keeping systems observable with Prometheus/Grafana and centralized logs. Day to day I partner with developers on reliable deploys, own monitoring/alerting hygiene, and handle incident recovery and backup/restore practice. I'm comfortable on Linux, networking basics, and working with security (ATTT) on hardening and findings. I'm interested in VNPT IT because the JD matches how I already work — fundamentals plus real production operations.",
      "Hãy giới thiệu về bản thân.",
      "Tôi là kỹ sư DevOps với kinh nghiệm hands-on xuyên vòng delivery: cộng tác Git, CI/CD kiểu Jenkins/GitLab, đóng gói Docker, vận hành workload Kubernetes, và quan sát hệ thống bằng Prometheus/Grafana cùng log tập trung. Hàng ngày tôi làm việc với developer về deploy ổn định, chăm sóc monitoring/alerting, xử lý sự cố và thực hành backup/restore. Tôi vững Linux, network cơ bản, và phối hợp ATTT về hardening/finding. Tôi quan tâm VNPT IT vì JD khớp cách tôi đang làm — nền tảng vững kèm vận hành production thật."),
    I("sec-fit", "Why VNPT / this DevOps role?", "JD match without inventing internals",
      "Why do you want this DevOps role at VNPT IT?",
      "Because the role description matches the work I want to deepen: build and run CI/CD with developers, operate Docker/Kubernetes including HA thinking, monitoring with Prometheus/Grafana/ELK, backup and recovery, and collaborate with ATTT. VNPT IT operates important services at scale in Vietnam, so strong fundamentals plus disciplined ops matter. I want to contribute on reliability and delivery speed without shortcuts on security.",
      "Tại sao bạn muốn role DevOps tại VNPT IT?",
      "Vì JD khớp việc tôi muốn đào sâu: xây/chạy CI/CD cùng developer, vận hành Docker/Kubernetes kể cả tư duy HA, giám sát Prometheus/Grafana/ELK, backup/recovery, và phối hợp ATTT. VNPT IT vận hành dịch vụ quan trọng quy mô lớn ở Việt Nam, nên nền tảng vững và ops kỷ luật rất quan trọng. Tôi muốn đóng góp vào độ tin cậy và tốc độ delivery mà không cắt góc bảo mật."),
    I("sec-fit", "Why should we hire you?", "Concrete strengths",
      "Why should we hire you?",
      "I can own the path from commit to healthy production: pipeline design, container packaging, Kubernetes rollout/rollback, and alert/runbook quality. I debug with evidence — logs, metrics, events — instead of guessing. I communicate clearly with developers and security, and I'm honest about what I've done hands-on versus what I'd ramp up. That combination reduces incident time and keeps delivery predictable.",
      "Tại sao nên tuyển bạn?",
      "Tôi own được đường từ commit đến production khỏe: thiết kế pipeline, đóng gói container, rollout/rollback Kubernetes, và chất lượng alert/runbook. Tôi debug bằng bằng chứng — log, metric, event — không đoán mò. Tôi giao tiếp rõ với developer và ATTT, và trung thực về phần đã hands-on versus phần sẽ học nhanh. Tổ hợp đó giảm thời gian sự cố và giữ delivery ổn định."),
    I("sec-fit", "Strengths and weakness", "Job-relevant",
      "What are your strengths and one weakness?",
      "Strength: practical incident and delivery ownership — I reproduce issues, isolate layer (CI vs runtime vs network vs data), mitigate first, then fix root cause and prevent with automation or better alerts. Another strength is translating between developers and ops constraints. Weakness: I can over-invest in polishing a runbook or pipeline when a smaller safe fix would unblock the business sooner. I've learned to time-box, ship the safe mitigation, then harden.",
      "Điểm mạnh và một điểm yếu?",
      "Mạnh: ownership sự cố và delivery thực tế — reproduce, cô lập lớp (CI/runtime/network/data), giảm hại trước, rồi root-cause và phòng ngừa bằng automation hoặc alert tốt hơn. Mạnh nữa là cầu nối giữa developer và ràng buộc ops. Yếu: đôi khi đầu tư quá nhiều để polish runbook/pipeline khi một fix nhỏ an toàn đã mở được việc. Tôi đã học time-box, ship mitigation an toàn, rồi harden sau."),
    I("sec-fit", "Tool stack walkthrough", "Jenkins to ELK in one answer",
      "Walk me through your DevOps tool stack.",
      "Source control and collaboration: Git with GitLab or Bitbucket, tickets in Jira. CI/CD: Jenkins and/or GitLab CI — build, test, scan, package images, deploy with approvals for prod. Config automation: Ansible and Bash/Python scripts. Runtime: Docker images on Kubernetes with Services/Ingress, probes, rolling updates. Edge: Nginx or Apache as reverse proxy/TLS. Observability: Prometheus metrics, Grafana dashboards, ELK for logs. Security: least privilege, secrets outside Git, work findings with ATTT. Backup: defined RPO/RTO and restore drills.",
      "Hãy mô tả stack DevOps của bạn.",
      "Source control/cộng tác: Git với GitLab hoặc Bitbucket, ticket Jira. CI/CD: Jenkins và/hoặc GitLab CI — build, test, scan, đóng image, deploy có approval cho prod. Tự động cấu hình: Ansible và script Bash/Python. Runtime: image Docker trên Kubernetes với Service/Ingress, probe, rolling update. Edge: Nginx hoặc Apache reverse proxy/TLS. Quan sát: Prometheus, Grafana, ELK. Bảo mật: least privilege, secret ngoài Git, xử lý finding với ATTT. Backup: RPO/RTO rõ và diễn tập restore."),
    I("sec-fit", "English comfort for DevOps work", "Docs, incidents, meetings",
      "How comfortable are you working in English?",
      "I'm comfortable reading English docs, writing runbooks and incident updates, and discussing technical tradeoffs in meetings. I may not be perfect, but I can explain pipelines, outages, and design choices clearly — which matters more than sounding fancy.",
      "Bạn làm việc bằng tiếng Anh thế nào?",
      "Tôi ổn với đọc docs tiếng Anh, viết runbook và cập nhật sự cố, cũng như thảo luận tradeoff kỹ thuật trong họp. Không hoàn hảo, nhưng giải thích được pipeline, outage và lựa chọn thiết kế rõ — điều đó quan trọng hơn nói hoa mỹ."),

    I("sec-scenario", "Broken CI/CD pipeline", "Debug under pressure",
      "A pipeline that was green yesterday is failing today. What do you do?",
      "I start with what changed: last commits, dependency bumps, runner/agent changes, secrets/expiry, registry auth. I open the first failing stage log, reproduce locally or on the same agent image if possible, and check whether it's flaky vs deterministic. I mitigate by reverting the breaking change or pinning the dependency if prod is blocked, communicate status, then add a guard (better test, cache key, secret rotation alert) so it doesn't repeat.",
      "Pipeline hôm qua xanh hôm nay đỏ. Bạn làm gì?",
      "Tôi bắt đầu từ thứ đã đổi: commit, bump dependency, thay đổi runner/agent, secret/expiry, auth registry. Mở log stage fail đầu tiên, reproduce local hoặc trên cùng image agent nếu được, phân biệt flaky vs deterministic. Giảm hại bằng revert hoặc pin dependency nếu prod bị chặn, thông báo status, rồi thêm guard (test tốt hơn, cache key, alert xoay secret) để không lặp lại.",
      "S: Pipeline package stage failed after dependency bump\nT: Unblock staging deploys same day\nA: Compared green/red logs, reproduced, pinned version, fixed cache key\nR: Pipeline green; added changelog note + alert on registry 401"),
    I("sec-scenario", "Kubernetes service unavailable", "Pods not Ready",
      "Users report the app is down. Kubernetes shows pods not Ready. How do you approach it?",
      "I check Deployment/Pod status and events, then logs --previous for crash loops. I verify readiness/liveness probes, image pull errors, ConfigMap/Secret mounts, resource pressure (Pending/OOM), and Service/Ingress endpoints. Mitigate with rollback if a release just went out. Confirm node/DNS/certificate issues at the edge. After recovery, write a short postmortem and tighten probes or resource requests if needed.",
      "User báo app down. Pod không Ready. Bạn xử lý thế nào?",
      "Tôi xem status/events Deployment/Pod, rồi logs --previous nếu crash loop. Kiểm tra probe readiness/liveness, lỗi image pull, mount ConfigMap/Secret, thiếu tài nguyên (Pending/OOM), và endpoint Service/Ingress. Nếu vừa release thì rollback. Kiểm tra thêm node/DNS/cert ở edge. Sau khi hồi phục, viết postmortem ngắn và siết probe hoặc request nếu cần.",
      "S: CrashLoop after bad ConfigMap\nT: Restore availability under 15 minutes\nA: kubectl describe/logs, rollout undo, fixed config in Git\nR: Service healthy; added config validation in CI"),
    I("sec-scenario", "Alert storm", "On-call hygiene",
      "You get flooded with alerts. How do you regain control?",
      "I identify the symptom alert that reflects user impact and silence or inhibit noisy children temporarily with a clear expiry. I check recent deploys and saturation metrics. I mitigate the blast (scale, rollback, shed load) before deep diving every page. Afterward I dedupe alerts, add inhibits, improve thresholds, and link runbooks so the next on-call isn't drowning.",
      "Bạn bị bão alert. Làm sao lấy lại kiểm soát?",
      "Tôi xác định alert triệu chứng phản ánh ảnh hưởng user, tạm silence/inhibit các alert con ồn với thời hạn rõ. Xem deploy gần đây và metric bão hòa. Giảm blast (scale, rollback, shed load) trước khi đào sâu từng page. Sau đó dedupe alert, thêm inhibit, chỉnh ngưỡng, gắn runbook để on-call sau không bị ngộp.",
      "S: Disk and latency pages stacked during batch job\nT: Stop paging storm while protecting SLO\nA: Inhibited child alerts, mitigated disk, retuned thresholds\nR: One actionable page path; runbook updated"),
    I("sec-scenario", "Failed backup restore", "RPO honesty",
      "A restore drill fails. What do you do?",
      "I stop experimenting on the last good copy. I preserve remaining backups, validate checksums/integrity, try an alternate copy or older point, and communicate the realistic RPO impact to stakeholders. I escalate storage/vendor if needed. Then I fix the backup pipeline (permissions, retention, catalog, consistency method) and schedule another drill until restore time meets RTO.",
      "Diễn tập restore thất bại. Bạn làm gì?",
      "Tôi dừng thử nghiệm trên bản tốt cuối. Bảo vệ các bản còn lại, kiểm tra checksum/toàn vẹn, thử bản khác hoặc điểm cũ hơn, và thông báo ảnh hưởng RPO thực tế cho stakeholder. Escalate storage/vendor nếu cần. Sau đó sửa pipeline backup (quyền, retention, catalog, phương pháp nhất quán) và lên lịch diễn tập lại đến khi thời gian restore đạt RTO.",
      "S: Incremental chain incomplete\nT: Prove recoverable backup for critical DB\nA: Used prior full + fixed agent; documented restore order\nR: Successful drill timed; monitoring on backup job failure"),
    I("sec-scenario", "Security finding with ATTT", "Collaborate, don't fight",
      "ATTT reports a critical CVE on an image you run. How do you respond?",
      "I acknowledge, confirm the affected image tags/hosts and real exposure (internet-facing? privileged?). I propose a remediation plan: patch/rebuild base image, roll out via CI, temporary compensating controls if needed. I give a clear ETA, track in Jira, verify with rescans, and close with evidence. If we must accept risk temporarily, I document owner and expiry with ATTT.",
      "ATTT báo CVE critical trên image bạn đang chạy. Bạn phản hồi thế nào?",
      "Tôi acknowledge, xác nhận tag/host ảnh hưởng và mức phơi nhiễm thật (public? privileged?). Đề xuất remediation: vá/rebuild base image, rollout qua CI, control bù tạm nếu cần. Đưa ETA rõ, theo dõi trên Jira, verify bằng rescan, đóng kèm bằng chứng. Nếu phải chấp nhận rủi ro tạm, ghi nhận owner và hạn với ATTT.",
      "S: Critical CVE in base image\nT: Remediate without long downtime\nA: Rebuilt image, scanned, rolling update, verified with ATTT\nR: Finding closed; CI gate for critical CVEs tightened"),
    I("sec-scenario", "Improve a fragile architecture", "DevOps contribution",
      "An app is a single VM with manual deploys and no alerts. What would you improve first?",
      "I'd prioritize: (1) observability — basic metrics/logs and a symptom alert; (2) versioned deploy path — Git + CI package + documented rollback; (3) remove snowflake config via Ansible/IaC; (4) move toward multi-instance behind LB or containers when the app is ready. Each step should cut risk measurably, not a big-bang rewrite.",
      "App đang chạy một VM, deploy tay, không alert. Bạn cải thiện gì trước?",
      "Tôi ưu tiên: (1) quan sát — metric/log cơ bản và alert triệu chứng; (2) đường deploy có version — Git + CI đóng gói + rollback được ghi; (3) bỏ config snowflake bằng Ansible/IaC; (4) tiến tới đa instance sau LB hoặc container khi app sẵn sàng. Mỗi bước giảm rủi ro đo được, không big-bang rewrite.",
      "S: Single VM snowflake\nT: Reduce outage risk in one quarter\nA: Added monitoring, CI deploy, Ansible baseline\nR: MTTR improved; next step multi-instance"),
    I("sec-scenario", "Disk full on production host", "Classic ops fire",
      "Production host hits 100% disk. What's your playbook?",
      "Mitigate: find large consumers with df/du, clear safe caches/logs, truncate carefully if a process still holds deleted files (restart writer). Protect the app if needed by shedding non-critical load. Then prevent: log rotation, retention, image GC, alerts at 80/90%, and capacity planning. Check inodes too, not only bytes.",
      "Host prod đầy disk 100%. Playbook của bạn?",
      "Giảm hại: tìm consumer lớn bằng df/du, xóa cache/log an toàn, truncate cẩn thận nếu process còn giữ file đã xóa (restart writer). Bảo vệ app bằng cách giảm tải không critical nếu cần. Phòng ngừa: rotate log, retention, GC image, alert 80/90%, capacity planning. Kiểm tra cả inode, không chỉ byte."),
    I("sec-scenario", "Nginx 502 after deploy", "Edge vs upstream",
      "After a deploy, Nginx returns 502. How do you debug?",
      "502 means Nginx couldn't get a valid response from upstream. I check nginx error log, upstream address/port, whether the new pods/processes are listening, readiness, TLS mismatch, and timeouts. I compare with the previous working upstream. Rollback the app or proxy config if needed, then fix the root cause (wrong Service port, probe never Ready, etc.).",
      "Sau deploy Nginx trả 502. Bạn debug thế nào?",
      "502 nghĩa là Nginx không nhận được phản hồi hợp lệ từ upstream. Tôi xem error log nginx, địa chỉ/port upstream, process/pod mới có listen không, readiness, lệch TLS, timeout. So với upstream đang chạy tốt trước đó. Rollback app hoặc config proxy nếu cần, rồi sửa gốc (sai port Service, probe không Ready, v.v.)."),

    I("sec-close", "Smart questions for VNPT", "Show judgment",
      "What questions do you have for us?",
      "How is the split between platform/shared CI work and product team embedding? What does on-call look like for this role? How do DevOps and ATTT collaborate on findings and change windows? Which parts of the stack are Jenkins vs GitLab CI today? How is the team adopting AI/LLM tools for engineering work, and what policies exist around secrets and review?",
      "Bạn muốn hỏi chúng tôi gì?",
      "Tỉ lệ việc platform/CI dùng chung versus embed vào product team thế nào? On-call của role này ra sao? DevOps và ATTT phối hợp finding và change window thế nào? Hiện stack đang Jenkins hay GitLab CI ở phần nào? Team đang áp dụng AI/LLM cho engineering ra sao, và policy về secret/review như thế nào?"),
    I("sec-close", "Questions about product and reliability", "Ops-focused curiosity",
      "Anything else you want to know about the work?",
      "Which services would I support first, and what are their current reliability pain points — deploy frequency, MTTR, or noisy alerts? How do you practice backup restore drills today? Is Kubernetes HA already multi-AZ for critical workloads, or is that a roadmap item?",
      "Bạn còn muốn biết gì về công việc?",
      "Tôi sẽ hỗ trợ service nào trước, và pain point độ tin cậy hiện tại là gì — tần suất deploy, MTTR, hay alert ồn? Hiện team diễn tập restore backup thế nào? Kubernetes HA đã multi-AZ cho workload critical chưa, hay đang là roadmap?"),
    I("sec-close", "60-second closing pitch", "Calm + honest + DevOps",
      "Anything else you'd like to add?",
      "Just briefly: I bring strong hands-on DevOps across CI/CD, Docker/Kubernetes, Linux/networking fundamentals, monitoring, and recovery. I work cleanly with developers and ATTT, debug with evidence, and use AI as a practical assistant with human review — not as a substitute for ownership. I'm excited about contributing to reliable delivery at VNPT IT and learning your estate the right way.",
      "Bạn còn muốn bổ sung gì?",
      "Ngắn gọn: tôi mang DevOps hands-on vững ở CI/CD, Docker/Kubernetes, nền tảng Linux/mạng, monitoring và recovery. Tôi làm việc rõ ràng với developer và ATTT, debug bằng bằng chứng, và dùng AI như trợ lý thực tế có review — không thay ownership. Tôi mong đóng góp vào delivery tin cậy tại VNPT IT và học hệ thống của team đúng cách."),
]
