# Caller: gen_vnpt.py (from cards_part1c import CARDS as C1C). Synthetic concept cards only.
# Shape: {sec, kind, title, sub, c_en, m_en, c_vi, m_vi, crib, note} — no date fields.
# User request: create interview-cheatsheet/vnpt-devops.html

def C(sec, title, sub, c_en, m_en, c_vi, m_vi, crib="", note=""):
    return {
        "sec": sec, "kind": "concept", "title": title, "sub": sub,
        "c_en": c_en, "m_en": m_en, "c_vi": c_vi, "m_vi": m_vi,
        "crib": crib, "note": note,
    }


CARDS = [
    C("sec-k8s", "Kubernetes building blocks", "Pod, Deployment, Service",
      "Pod = smallest schedulable unit (one+ containers). Deployment manages replica Pods and rolling updates. Service provides stable virtual IP/DNS to Pods.",
      "Labels/selectors glue objects together.",
      "Pod = đơn vị nhỏ nhất. Deployment quản lý replica và rolling update. Service cho VIP/DNS ổn định tới Pod.",
      "Label/selector gắn các object.",
      "Creating bare Pods in prod instead of controllers is an anti-pattern.",
      "kubectl get pods,deploy,svc -A\nkubectl describe pod <name>"),
    C("sec-k8s", "ConfigMap and Secret", "Config injection",
      "ConfigMap for non-secret config; Secret for sensitive data (still base64 in etcd unless encrypted/KMS). Mount as env or files; do not bake into images.",
      "Updates may need rollout restart depending on consumption method.",
      "ConfigMap cho config không mật; Secret cho dữ liệu nhạy cảm (base64 trừ khi mã hóa/KMS). Mount env/file; đừng nhét vào image.",
      "Update có thể cần rollout restart tùy cách app đọc.",
      "Putting DB passwords in ConfigMap is wrong.",
      "kubectl create configmap app-cfg --from-literal=LOG_LEVEL=info\nkubectl create secret generic app-db --from-literal=password=..."),
    C("sec-k8s", "Probes: liveness, readiness, startup", "Health semantics",
      "Readiness: ready for traffic. Liveness: restart if stuck. Startup: slow boot grace. Wrong probes cause flapping or blackhole traffic.",
      "Health endpoints should check critical deps carefully (avoid cascading failures).",
      "Readiness: sẵn sàng nhận traffic. Liveness: restart nếu kẹt. Startup: cho boot chậm. Probe sai gây flap hoặc mất traffic.",
      "Endpoint health kiểm tra dependency cẩn thận (tránh lỗi dây chuyền).",
      "Liveness hitting a dependency so DB blip kills all pods is a classic mistake.",
      "kubectl get pods\nkubectl describe pod <p>"),
    C("sec-k8s", "Rolling updates and rollback", "Safe changes",
      "Deployments update Pods gradually (maxUnavailable/maxSurge). Roll back with kubectl rollout undo if bad release.",
      "Keep migrations backward-compatible for rolling updates.",
      "Deployment cập nhật Pod dần (maxUnavailable/maxSurge). Rollback bằng rollout undo nếu lỗi.",
      "Migration DB cần tương thích ngược khi rolling.",
      "Breaking API schema mid-rollout with mixed old/new pods causes partial outages.",
      "kubectl rollout status deploy/api\nkubectl rollout history deploy/api\nkubectl rollout undo deploy/api"),
    C("sec-k8s", "Ingress and Service types", "Exposing apps",
      "ClusterIP (internal), NodePort, LoadBalancer, ExternalName. Ingress (or Gateway API) routes L7 HTTP to Services; often TLS terminates here.",
      "Know that Ingress needs a controller (nginx/traefik/cloud).",
      "ClusterIP nội bộ; NodePort; LoadBalancer; ExternalName. Ingress định tuyến HTTP L7 tới Service; thường terminate TLS.",
      "Ingress cần controller.",
      "Creating Ingress without a controller means nothing listens.",
      "kubectl get ingress,svc\nkubectl describe ingress app"),
    C("sec-k8s", "Requests, limits, QoS", "Scheduling and eviction",
      "requests influence scheduling; limits cap usage. CPU throttling vs OOMKill for memory. Set realistic requests from metrics.",
      "HPA scales on metrics when configured; without headroom, pending pods appear.",
      "requests ảnh hưởng lịch; limits trần sử dụng. CPU throttle vs OOMKill. Đặt request theo metrics thật.",
      "HPA scale theo metric khi cấu hình; thiếu tài nguyên → pod Pending.",
      "No requests → noisy neighbor; huge requests → waste/pending.",
      "kubectl top pods"),
    C("sec-k8s", "HA patterns on Kubernetes", "What HA means in practice",
      "App HA: multiple replicas across nodes/AZs, PodDisruptionBudget, anti-affinity, readiness gates, multi-replica control plane for the cluster itself.",
      "Data HA is harder: managed DB multi-AZ, replicas, backups — not just replicas: 3 on a single-node PVC app.",
      "HA app: nhiều replica trên nhiều node/AZ, PDB, anti-affinity, readiness. Control plane cũng cần HA.",
      "HA dữ liệu khó hơn: DB multi-AZ, replica, backup — không chỉ replicas: 3 với PVC một node.",
      "3 replicas all scheduled on one node due to missing anti-affinity is fake HA.",
      "kubectl get pdb\nkubectl get pods -o wide"),
    C("sec-k8s", "Namespaces, RBAC, quotas", "Multi-team hygiene",
      "Namespaces isolate resources logically. RBAC grants least privilege. ResourceQuota/LimitRange prevent one team from eating the cluster.",
      "ServiceAccounts for pods; avoid using cluster-admin for apps.",
      "Namespace cô lập logic. RBAC cấp quyền tối thiểu. Quota/LimitRange tránh một team chiếm cluster.",
      "Pod dùng ServiceAccount; tránh cluster-admin cho app.",
      "Granting cluster-admin to CI bots permanently is dangerous.",
      "kubectl auth can-i create deployments --as=system:serviceaccount:ns:sa -n ns"),
    C("sec-k8s", "kubectl debug loop", "First 5 minutes",
      "get/describe/logs/events; check image pull errors, CrashLoopBackOff, Pending (resources/taints), probe failures, config mistakes.",
      "Use previous logs for crash loops: kubectl logs --previous.",
      "get/describe/logs/events; kiểm tra image pull, CrashLoopBackOff, Pending, probe, config sai.",
      "Crash loop: kubectl logs --previous.",
      "Deleting pods repeatedly without reading events wastes time.",
      "kubectl get events --sort-by=.lastTimestamp | tail\nkubectl logs deploy/api --tail=200\nkubectl logs pod/x --previous"),
    C("sec-k8s", "Jobs, CronJobs, DaemonSets (awareness)", "Other controllers",
      "Job/CronJob for batch; DaemonSet per-node agents (logs/monitoring); StatefulSet for identity/storage needing stable names.",
      "Pick controller by workload shape.",
      "Job/CronJob cho batch; DaemonSet agent mỗi node; StatefulSet khi cần tên/storage ổn định.",
      "Chọn controller theo kiểu workload.",
      "Using Deployment for a DB that needs stable storage without understanding StatefulSet/operators is risky.",
      "kubectl get cronjobs,daemonsets,statefulsets -A"),

    C("sec-web", "Nginx as reverse proxy", "Most common pattern",
      "Nginx terminates client HTTP(S), proxies to upstream app/containers, can load-balance, cache, rate-limit, serve static files.",
      "Know proxy_pass, upstream blocks, and that trailing slashes change URI joining behavior.",
      "Nginx nhận HTTP(S) từ client, proxy tới app/container, có thể LB, cache, rate-limit, static.",
      "Biết proxy_pass, upstream, và dấu / cuối ảnh hưởng nối URI.",
      "502/504 blamed on app when upstream address/port is wrong is common.",
      "nginx -t && systemctl reload nginx\ncurl -I http://127.0.0.1/health"),
    C("sec-web", "Apache httpd awareness", "Still in many enterprises",
      "Apache is a mature HTTP server with virtual hosts, modules (mod_proxy, mod_ssl), .htaccess in some setups. Same reverse-proxy role as Nginx in many JD contexts.",
      "Compare: Nginx event-driven often lighter for static/proxy; Apache module ecosystem historically richer — pick by estate.",
      "Apache là HTTP server chín với virtual host, module (mod_proxy, mod_ssl), đôi khi .htaccess. Cùng vai trò reverse proxy như Nginx trong nhiều JD.",
      "So sánh: Nginx event-driven thường nhẹ cho static/proxy; Apache hệ module giàu — chọn theo hệ thống sẵn có.",
      "Enabling .htaccess overrides everywhere hurts performance and surprises config.",
      "apachectl configtest\nsystemctl reload httpd || systemctl reload apache2"),
    C("sec-web", "SSL termination patterns", "Where TLS ends",
      "TLS can terminate at LB, at Nginx/Apache edge, or end-to-end to the app. Enterprises often terminate at edge and use internal HTTP/mTLS behind.",
      "Reload/restart gracefully after cert rotation; keep intermediate chain complete.",
      "TLS có thể terminate ở LB, ở Nginx/Apache, hoặc xuyên tới app. Doanh nghiệp thường terminate ở edge.",
      "Reload mượt sau xoay cert; đủ chuỗi intermediate.",
      "Missing intermediate cert → some mobile clients fail only.",
      "nginx -t && systemctl reload nginx"),
    C("sec-web", "Upstreams to containers/K8s", "Dynamic backends",
      "Point proxy to Service DNS or ingress. Watch timeouts, idle connections, and header forwarding (X-Forwarded-For, X-Forwarded-Proto).",
      "Health checks at proxy and K8s readiness should align.",
      "Trỏ proxy tới Service DNS hoặc ingress. Chú ý timeout, idle connection, header X-Forwarded-*.",
      "Health check ở proxy và readiness K8s nên khớp.",
      "Caching forever at edge after deploy — purge or short TTL for HTML."),
    C("sec-web", "Access/error logs and status codes", "Ops reading",
      "Access log: who/what/latency. Error log: upstream failures. Codes: 502 bad gateway, 503 unavailable, 504 gateway timeout, 4xx client, 5xx server.",
      "Correlate with app logs by request id if available.",
      "Access log: ai/gì/latency. Error log: lỗi upstream. 502/503/504/4xx/5xx.",
      "Tương quan với app log bằng request id nếu có.",
      "Rate of 200s while users fail on another path — check the right vhost/location.",
      "tail -f /var/log/nginx/access.log /var/log/nginx/error.log"),
    C("sec-web", "Config hygiene", "Test before reload",
      "Always nginx -t / apachectl configtest before reload. Use reload for graceful worker pickup; reserve restart for harder cases.",
      "Keep configs in Git/Ansible; avoid snowflake edits on prod only.",
      "Luôn nginx -t / apachectl configtest trước reload. Ưu tiên reload; restart khi cần.",
      "Giữ config trong Git/Ansible; tránh sửa tay chỉ trên prod.",
      "Reload without test can take down workers on syntax error.",
      "nginx -t && systemctl reload nginx"),

    C("sec-monitor", "Prometheus model", "Metrics, labels, pull",
      "Prometheus scrapes metrics (pull) from exporters/apps; stores time series; PromQL queries; Alertmanager routes alerts.",
      "USE/RED methods help choose metrics: Utilization/Saturation/Errors; Rate/Errors/Duration for services.",
      "Prometheus scrape (pull) metrics từ exporter/app; lưu time series; PromQL; Alertmanager định tuyến cảnh báo.",
      "USE/RED giúp chọn metric.",
      "High-cardinality labels (user_id) explode memory.",
      "up{job=\"api\"}\nrate(http_requests_total[5m])\nhistogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))"),
    C("sec-monitor", "Grafana dashboards", "Visualize and share",
      "Grafana visualizes Prometheus (and other) data sources; dashboards for golden signals; variables for env/cluster; share links in incidents.",
      "Dashboards do not replace alerts — they support diagnosis.",
      "Grafana trực quan hóa Prometheus (và nguồn khác); dashboard golden signals; biến env/cluster; chia sẻ khi sự cố.",
      "Dashboard không thay alert — hỗ trợ chẩn đoán.",
      "40-panel dashboards nobody understands during a page are useless."),
    C("sec-monitor", "Alerting hygiene", "Pages that matter",
      "Alert on symptoms tied to SLOs (error rate, latency, saturation) plus a few cause alerts. Every alert needs owner + runbook. Suppress flapping; use inhibit rules.",
      "Severity: page vs ticket vs log. Quiet hours only for non-customer impact if policy allows.",
      "Alert theo triệu chứng gắn SLO + vài alert nguyên nhân. Mỗi alert cần owner + runbook. Chống flap; inhibit.",
      "Mức độ: page vs ticket vs log.",
      "Paging on CPU > 70% with no user impact trains alert fatigue."),
    C("sec-monitor", "ELK pipeline", "Elasticsearch, Logstash/Fluent, Kibana",
      "Logs ship via Filebeat/Fluent Bit/Logstash → Elasticsearch → Kibana for search/visualize. Structure logs (JSON) with request ids.",
      "Control volume/retention/index lifecycle or costs explode.",
      "Log đi Filebeat/Fluent/Logstash → Elasticsearch → Kibana. Ưu tiên log JSON có request id.",
      "Kiểm soát volume/retention/ILM kẻo cháy chi phí.",
      "Indexing debug logs from all pods at trace level in prod is expensive noise."),
    C("sec-monitor", "Metrics vs logs vs traces", "Three pillars",
      "Metrics: cheap aggregation, great for alerts. Logs: detail for debugging. Traces: request path across services. Use together.",
      "Start with metrics+logs if tracing is not ready; still correlate by time and ids.",
      "Metric: rẻ, tốt cho alert. Log: chi tiết debug. Trace: đường đi request. Dùng kết hợp.",
      "Chưa có tracing thì vẫn metric+log, tương quan theo thời gian và id.",
      "Only grepping logs during latency incidents without saturation metrics is incomplete."),
    C("sec-monitor", "Exporters and instrumentation", "Getting data in",
      "Node exporter for host metrics; blackbox for probes; app metrics via client libraries (/metrics). Naming and labels need conventions.",
      "Health endpoints are not the same as Prometheus metrics, but both useful.",
      "Node exporter cho host; blackbox probe; app expose /metrics. Cần convention tên/label.",
      "Health endpoint không phải metric Prometheus, nhưng cả hai hữu ích.",
      "Scraping every 5s with huge payloads overloads Prometheus and targets.",
      "curl -s localhost:9100/metrics | head"),
    C("sec-monitor", "On-call hygiene", "Human side of monitoring",
      "Clear escalation, handoff notes, status page updates, blameless postmortems, track action items. Reduce toil with better alerts and automation.",
      "During incident: mitigate first, root-cause second, communicate always.",
      "Escalation rõ, ghi chú bàn giao, cập nhật status, postmortem không đổ lỗi, theo dõi action. Giảm toil bằng alert/automation tốt hơn.",
      "Khi sự cố: giảm hại trước, root-cause sau, luôn giao tiếp.",
      "Hero culture without fixing alert quality burns the team."),
    C("sec-monitor", "Example alert thoughts", "Interview-ready examples",
      "Examples: API 5xx rate > 2% for 5m; p95 latency > SLO; disk < 15%; Kafka lag; certificate expiry < 14d; K8s CrashLoopBackOff count; backup job failed.",
      "Each should link a runbook step list.",
      "Ví dụ: tỉ lệ 5xx API > 2% trong 5p; p95 > SLO; disk < 15%; lag Kafka; cert < 14 ngày; CrashLoopBackOff; job backup fail.",
      "Mỗi alert gắn runbook.",
      "Alert with no next step trains people to ignore pages."),

    C("sec-backup", "RPO and RTO", "Business numbers first",
      "RPO (Recovery Point Objective): how much data loss is tolerable (time). RTO (Recovery Time Objective): how fast service must return. Backups/HA design follow these.",
      "HA reduces RTO for many failures; backups address data loss/corruption/region loss.",
      "RPO: mất dữ liệu chấp nhận được (theo thời gian). RTO: thời gian dịch vụ phải trở lại. Thiết kế backup/HA theo các số này.",
      "HA giảm RTO cho nhiều lỗi; backup xử lý mất/hỏng dữ liệu/mất region.",
      "Daily backups when RPO is 15 minutes is a design mismatch."),
    C("sec-backup", "Full, incremental, differential", "Backup types",
      "Full: everything. Incremental: changes since last backup (any type). Differential: changes since last full. Trade storage vs restore complexity/time.",
      "Document restore order; test it.",
      "Full: toàn bộ. Incremental: thay đổi từ bản gần nhất. Differential: từ bản full gần nhất. Đổi lưu trữ vs độ phức tạp restore.",
      "Ghi rõ thứ tự restore; phải test.",
      "Never-tested incremental chain that fails at restore time is common."),
    C("sec-backup", "3-2-1 idea", "Resilience of copies",
      "Classic guidance: 3 copies, 2 media types, 1 offsite/offline (adapt to cloud: multi-account/region + immutability).",
      "Ransomware-aware: immutable/object-lock backups matter.",
      "Hướng dẫn cổ điển: 3 bản, 2 loại media, 1 offsite/offline (cloud: đa account/region + immutability).",
      "Chống ransomware: backup bất biến quan trọng.",
      "Only snapshots on the same disk array as primary = correlated failure."),
    C("sec-backup", "Restore testing", "Backup is not restore",
      "A backup without restore tests is hope. Schedule restore drills; measure time; fix automation gaps; verify app consistency (DB checksums/smoke).",
      "Include credentials, DNS cutover, and secrets in the drill scope when relevant.",
      "Backup không test restore chỉ là hy vọng. Lịch diễn tập; đo thời gian; vá lỗ hổng; kiểm tra tính nhất quán app/DB.",
      "Diễn tập gồm cả credential, DNS, secret khi liên quan.",
      "Testing file presence only, not application boot + query, is incomplete."),
    C("sec-backup", "K8s / volumes / DB angles", "What to back up",
      "Cluster etcd (control plane), PVCs/volume snapshots, container images in registry, and especially databases (logical dumps + snapshots). App config in Git helps rebuild.",
      "Stateless apps rebuild from Git+registry; stateful needs explicit strategy.",
      "Cần backup etcd, PVC/snapshot, image registry, đặc biệt database (dump + snapshot). Config app trong Git giúp dựng lại.",
      "App stateless dựng lại từ Git+registry; stateful cần chiến lược riêng.",
      "Snapshotting a busy DB volume without freeze/consistent strategy risks bad backups.",
      "pg_dump -Fc db > db.dump\n# restore drills in non-prod first"),
    C("sec-backup", "Failed restore incident mindset", "When drill or real restore fails",
      "Stop, preserve remaining copies, check integrity, try alternate copy/region, communicate RPO impact, escalate vendors if needed, write postmortem with backup pipeline fixes.",
      "Never overwrite last good backup while experimenting.",
      "Dừng lại, bảo vệ bản còn lại, kiểm tra toàn vẹn, thử bản/region khác, thông báo ảnh hưởng RPO, escalate nếu cần, postmortem sửa pipeline backup.",
      "Không ghi đè bản backup tốt cuối khi thử nghiệm.",
      "Repeated restore attempts destroying the only good copy is catastrophic."),

    C("sec-arch", "Layered system view", "Client to data",
      "Typical layers: clients → DNS/CDN → load balancer/WAF → reverse proxy/ingress → app services → caches/queues → databases/storage → observability.",
      "DevOps contributes by making each layer deployable, observable, and recoverable.",
      "Các lớp điển hình: client → DNS/CDN → LB/WAF → reverse proxy/ingress → app → cache/queue → DB/storage → observability.",
      "DevOps giúp mỗi lớp deploy được, quan sát được, phục hồi được.",
      "Drawing boxes without failure modes and ownership is incomplete architecture."),
    C("sec-arch", "Deploy topologies", "Single host to multi-AZ",
      "Evolve: single VM → multiple VMs behind LB → containers on K8s → multi-AZ. Each step changes failure domains and ops complexity.",
      "Do not skip basic monitoring when chasing fancy topology.",
      "Tiến hóa: một VM → nhiều VM sau LB → container trên K8s → multi-AZ. Mỗi bước đổi failure domain và độ phức tạp ops.",
      "Đừng bỏ monitoring cơ bản khi chạy theo topology phức tạp.",
      "Multi-AZ apps with single-AZ database still have SPOF."),
    C("sec-arch", "Scaling basics", "Vertical vs horizontal",
      "Vertical: bigger machine — simple limits. Horizontal: more replicas — needs statelessness or sticky/session strategy + scalable data tier.",
      "Autoscale on meaningful metrics; load test before big events.",
      "Dọc: máy lớn hơn — đơn giản nhưng có trần. Ngang: nhiều replica — cần stateless hoặc sticky + tầng dữ liệu scale được.",
      "Autoscale theo metric có nghĩa; load test trước sự kiện lớn.",
      "Scaling web tier into a tiny DB just moves the bottleneck."),
    C("sec-arch", "Reliability basics", "SLI/SLO/SLA awareness",
      "SLI: measured indicator. SLO: target. SLA: contractual consequences. Error budgets guide release speed vs stability.",
      "Design for graceful degradation (read-only mode, cache fallback).",
      "SLI: chỉ số đo. SLO: mục tiêu. SLA: cam kết/hậu quả hợp đồng. Error budget cân bằng tốc độ release vs ổn định.",
      "Thiết kế giảm cấp (read-only, fallback cache).",
      "100% uptime SLO is unrealistic and drives bad decisions."),
    C("sec-arch", "HA vs DR", "Related but different",
      "HA: withstand component failures with minimal downtime (redundancy). DR: recover from major site/region loss (backups, failover runbooks, RPO/RTO).",
      "DR needs people drills, not only replicated disks.",
      "HA: chịu lỗi thành phần với downtime thấp (dư thừa). DR: phục hồi khi mất site/region (backup, runbook failover, RPO/RTO).",
      "DR cần diễn tập con người, không chỉ disk replicate.",
      "Calling multi-replica Deployment a complete DR plan is wrong."),
    C("sec-arch", "Contributing as DevOps to architecture", "How to speak in design reviews",
      "Bring operational constraints: deployability, observability, blast radius, secret flows, capacity, cost, ATTT requirements, backup strategy.",
      "Propose incremental improvements with measurable risk reduction.",
      "Mang ràng buộc vận hành: khả năng deploy, quan sát, blast radius, luồng secret, capacity, chi phí, yêu cầu ATTT, chiến lược backup.",
      "Đề xuất cải tiến dần với giảm rủi ro đo được.",
      "Architecture astronauting without ops evidence does not help."),

    C("sec-lang", "Bash for daily ops", "What know Bash means on JD",
      "Enough to write safe automation: loops, functions, exit codes, text processing, calling CLIs (kubectl, aws, docker), cron entrypoints.",
      "Not a full software engineering language course — practical scripting.",
      "Đủ để viết automation an toàn: vòng lặp, hàm, exit code, xử lý text, gọi CLI, entrypoint cron.",
      "Không phải khóa lập trình đầy đủ — scripting thực dụng.",
      "500-line Bash where Python would be clearer — know when to switch."),
    C("sec-lang", "Python for automation and APIs", "Glue language",
      "Use for REST API calls, parsing inventory, generating configs, cloud SDKs, simple policy checks. Understand venv, pip, exceptions, JSON.",
      "Readable scripts with logging beat clever one-liners.",
      "Dùng gọi REST, parse inventory, sinh config, SDK cloud, kiểm tra policy đơn giản. Hiểu venv, pip, exception, JSON.",
      "Script dễ đọc có logging hơn one-liner hay.",
      "Committing .venv or secrets in settings files is a fail.",
      "import requests, json, sys"),
    C("sec-lang", "Java awareness for DevOps", "Enough to support app teams",
      "Know jars/wars, JVM memory flags vs container limits, common build tools (Maven/Gradle), 12-factor config via env, heap dumps/GC logs for incidents.",
      "You are not asked to be a Java architect — support packaging, config, and runtime health.",
      "Biết jar/war, flag bộ nhớ JVM vs limit container, Maven/Gradle, config qua env, heap dump/GC log khi sự cố.",
      "Không cần là kiến trúc sư Java — hỗ trợ đóng gói, config, sức khỏe runtime.",
      "Setting -Xmx larger than container memory limit causes OOM.",
      "java -Xms256m -Xmx512m -jar app.jar"),
    C("sec-lang", "Reading others code under pressure", "Ops skill",
      "DevOps often reads app configs, Dockerfiles, Helm values, pipeline YAML, small scripts. Focus on inputs/outputs, env vars, failure paths.",
      "Ask app owners for invariants (timeouts, idempotency) before changing runtime.",
      "DevOps thường đọc config app, Dockerfile, Helm values, YAML pipeline, script nhỏ. Tập trung input/output, env, nhánh lỗi.",
      "Hỏi owner về bất biến (timeout, idempotency) trước khi đổi runtime.",
      "Changing retry/timeout without understanding double-charge risks is dangerous."),
    C("sec-lang", "When to choose which language", "Practical decision",
      "Bash: thin glue around CLIs. Python: logic, APIs, data shaping. Ansible: host config drift. Existing team language: prefer consistency for shared tools.",
      "Optimize for maintainability by on-call engineers.",
      "Bash: glue quanh CLI. Python: logic/API/data. Ansible: drift cấu hình host. Ngôn ngữ team sẵn có: ưu tiên đồng nhất.",
      "Tối ưu khả năng maintain bởi người on-call.",
      "Introducing a new language for a 20-line tool nobody else can edit is a tax."),

    C("sec-ai", "AI/LLM in DevOps — JD framing", "Practical, not hype",
      "Use LLMs as assistants: draft scripts, explain unfamiliar errors, summarize long logs, improve runbooks/docs, suggest pipeline YAML — always with human review before prod.",
      "Do not claim you built or operate a production LLM platform unless that is true. Frame as productivity tooling with guardrails.",
      "Dùng LLM như trợ lý: phác script, giải thích lỗi lạ, tóm tắt log dài, cải thiện runbook/docs, gợi ý YAML pipeline — luôn có người review trước prod.",
      "Không nhận xây/vận hành nền tảng LLM production nếu chưa làm. Nói là tooling tăng năng suất có kiểm soát.",
      "Pasting secrets/PII into public LLM chats is a security failure."),
    C("sec-ai", "Assist CI/CD with AI carefully", "Where it helps",
      "Useful: explaining failed job logs, drafting Jenkinsfile/.gitlab-ci.yml stubs, suggesting test stages, writing clearer commit/changelog text.",
      "Still verify syntax, secrets handling, and that gates match team policy. AI can invent flags/plugins that do not exist.",
      "Hữu ích: giải thích log job fail, phác Jenkinsfile/.gitlab-ci.yml, gợi ý stage test, viết changelog rõ hơn.",
      "Vẫn phải verify cú pháp, xử lý secret, và gate khớp policy team. AI có thể bịa flag/plugin không tồn tại.",
      "Blindly merging AI-generated pipelines without dry-run is reckless."),
    C("sec-ai", "Log analysis and incident assist", "Human stays owner",
      "Paste redacted snippets to get hypotheses (OOM? probe? DNS?). Cross-check with metrics/events. AI speeds triage; you own the decision and communication.",
      "Keep a checklist: what changed, blast radius, mitigate, evidence, next check.",
      "Dán snippet đã redacted để lấy giả thuyết (OOM? probe? DNS?). Đối chiếu metrics/events. AI tăng tốc triage; bạn chịu trách nhiệm quyết định và giao tiếp.",
      "Giữ checklist: gì đã đổi, blast radius, giảm hại, bằng chứng, bước kiểm tra tiếp.",
      "Letting AI write the customer status update without verifying facts risks misinformation."),
    C("sec-ai", "Docs, IaC, and scripts", "Draft then harden",
      "AI can draft Ansible tasks, Bash wrappers, PromQL ideas, nginx snippets. You harden: idempotency, quoting, least privilege, tests in non-prod.",
      "Prefer small diffs and code review over large AI dumps.",
      "AI có thể phác task Ansible, Bash, ý tưởng PromQL, snippet nginx. Bạn harden: idempotency, quote, least privilege, test non-prod.",
      "Ưu tiên diff nhỏ và code review hơn dump AI lớn.",
      "Accepting AI output that hardcodes credentials is an instant fail."),
    C("sec-ai", "Limits and human review", "What to say in interview",
      "Limits: hallucinations, outdated APIs, missing org context, secret leakage risk, overconfidence. Policy: never apply AI changes to prod without review/tests.",
      "Interview line: I use AI daily as a pair for first drafts and explanations, then I verify with docs, dry-runs, and peer review.",
      "Giới hạn: ảo giác, API cũ, thiếu ngữ cảnh org, rủi ro lộ secret, tự tin quá mức. Policy: không áp AI lên prod khi chưa review/test.",
      "Câu phỏng vấn: tôi dùng AI hàng ngày như cặp để phác thảo và giải thích, rồi verify bằng docs, dry-run và peer review.",
      "Claiming AI replaces on-call judgment is a red flag."),
    C("sec-ai", "VNPT JD AI keyword coverage", "Stay honest",
      "JD likely wants awareness that AI/LLM can support DevOps workflows (CI help, log triage, docs). Show concrete personal workflows, not buzzwords.",
      "If asked about internal VNPT AI systems: you do not invent them — ask how the team adopts AI and what policies exist.",
      "JD có thể muốn thấy nhận thức AI/LLM hỗ trợ workflow DevOps (CI, log, docs). Nói workflow cá nhân cụ thể, không buzzword.",
      "Nếu hỏi hệ AI nội bộ VNPT: không bịa — hỏi team đang áp dụng AI thế nào và policy ra sao.",
      "Inventing VNPT-internal LLM platforms destroys trust."),
]
