# Caller: gen_vnpt.py — from cards_tips_mcq import CARDS as CTIPS
# VNPTips #2 exam strategy + MCQ drill cards. Synthetic study content; no dates.


def C(sec, title, sub, c_en, m_en, c_vi, m_vi, crib="", note=""):
    return {
        "sec": sec, "kind": "concept", "title": title, "sub": sub,
        "c_en": c_en, "m_en": m_en, "c_vi": c_vi, "m_vi": m_vi,
        "crib": crib, "note": note,
    }


def M(sec, title, sub, q_en, opts_en, ans_en, q_vi, opts_vi, ans_vi, crib=""):
    return {
        "sec": sec, "kind": "mcq", "title": title, "sub": sub,
        "q_en": q_en, "opts_en": opts_en, "ans_en": ans_en,
        "q_vi": q_vi, "opts_vi": opts_vi, "ans_vi": ans_vi,
        "crib": crib,
    }


CARDS = [
    C("sec-tips", "VNPTips #2: exam format", "Trắc nghiệm — what VNPT evaluates",
      "VNPT tuyển dụng tip: the screening test is usually multiple choice (trắc nghiệm). It evaluates specialized knowledge, logical thinking, and applying knowledge to real work — not only memorization.",
      "Expect three flavors: (1) foundational theory of the specialty, (2) situational questions for problem-solving, (3) practical application tied to the job (for you: DevOps/system).",
      "Theo VNPTips #2: bài thi tuyển thường là trắc nghiệm. Đánh giá năng lực chuyên môn, tư duy logic, và khả năng ứng dụng kiến thức vào thực tế — không chỉ học thuộc.",
      "Ba hướng câu hỏi: (1) lý thuyết nền tảng chuyên ngành, (2) tình huống tư duy/xử lý vấn đề, (3) ứng dụng thực tế gắn vị trí (DevOps/hệ thống).",
      "Studying only interview STAR stories is not enough — drill definitions and pick-the-best-option logic."),
    C("sec-tips", "Study by role focus", "DevOps / system / cloud track",
      "VNPT tip: study knowledge tied to the role you applied for. For Dev Java → backend/Java. For system, cloud, DevOps, DB → corresponding specialty knowledge.",
      "Your focus list: Linux + OS fundamentals, network/security basics, Git/CI/CD (Jenkins/GitLab), Docker/K8s HA, Nginx/Apache, Prometheus/Grafana/ELK, backup/RPO-RTO, Ansible/Bash/Python, AI/LLM applied to ops.",
      "Tip VNPT: ôn đúng kiến thức theo vị trí. Dev Java → Backend/Java. Hệ thống/cloud/DevOps/DB → kiến thức lĩnh vực tương ứng.",
      "Trọng tâm của bạn: Linux + OS, mạng/bảo mật cơ bản, Git/CI/CD (Jenkins/GitLab), Docker/K8s HA, Nginx/Apache, Prometheus/Grafana/ELK, backup/RPO-RTO, Ansible/Bash/Python, AI/LLM cho ops.",
      "Random deep Java collections study is low ROI for this JD unless a question mixes app + deploy."),
    C("sec-tips", "MCQ logic: eliminate then choose", "Read carefully",
      "VNPT tip: read the question and all options; eliminate unreasonable answers; pick the most accurate and logical option — not the first familiar buzzword.",
      "Watch absolute words (always/never), options that skip evidence (logs/metrics), and options that break security (secrets in Git, skip ATTT).",
      "Tip VNPT: đọc kỹ câu hỏi và phương án; loại đáp án không hợp lý; chọn phương án chính xác và logic nhất — không chọn buzzword quen thuộc đầu tiên.",
      "Cẩn thận từ tuyệt đối (always/never), đáp án bỏ qua bằng chứng (log/metric), và đáp án phá bảo mật (secret trong Git, bỏ qua ATTT).",
      "Two options can be partly true — choose the one that matches the scenario constraints."),
    C("sec-tips", "Time strategy for trắc nghiệm", "Score the easy ones first",
      "VNPT tip: do easy questions first to secure points; mark hard ones and return; avoid sinking too much time on one item; manage time to finish the whole paper.",
      "Micro habit: first pass = confident answers; second pass = marked; last minutes = review doubtful + ensure no blanks.",
      "Tip VNPT: làm câu dễ trước để giữ điểm; đánh dấu câu khó quay lại; tránh treo quá lâu một câu; quản lý thời gian để làm hết bài.",
      "Thói quen: vòng 1 = câu chắc; vòng 2 = câu đã đánh dấu; phút cuối = soát câu phân vân + không bỏ sót.",
      "Leaving blanks when guessing is usually worse than an educated guess if there is no penalty — confirm the rule on test day."),
    C("sec-tips", "Final review before submit", "Last minutes matter",
      "VNPT tip: if time remains, recheck selected answers, revisit unsure items, ensure no skipped questions. A short review can raise accuracy a lot.",
      "Also re-read questions you answered very fast — misreading 'NOT' / 'EXCEPT' is a classic trap.",
      "Tip VNPT: nếu còn thời gian, soát đáp án đã chọn, xem lại câu phân vân, đảm bảo không bỏ sót. Một bước kiểm tra nhỏ có thể tăng độ chính xác rõ rệt.",
      "Đọc lại câu trả lời quá nhanh — bẫy kinh điển là bỏ sót NOT / EXCEPT / không đúng.",
      "Changing answers without a clear reason often hurts — only change when you find a concrete mistake."),
    C("sec-tips", "Mindset on test day", "Calm · clear · finish",
      "VNPT closing message: prepare the right knowledge, understand the exam format, use a strategy — be confident, calm, and push through.",
      "For DevOps MCQ: think 'what would a careful on-call engineer do?' — isolate, evidence, least privilege, rollback-safe, measurable.",
      "Thông điệp VNPT: chuẩn bị đúng kiến thức, hiểu hình thức thi, làm bài có chiến lược — tự tin, bình tĩnh, bứt phá.",
      "Với MCQ DevOps: nghĩ 'kỹ sư on-call cẩn thận sẽ làm gì?' — cô lập, bằng chứng, least privilege, an toàn rollback, đo được.",
      "Panic-picking the longest option is not a strategy."),

    M("sec-tips", "MCQ: CI vs CD", "Theory",
      "Which statement best describes Continuous Integration (CI)?",
      "A) Automatically deploying every commit straight to production with no tests\nB) Automatically building and testing each change so the shared branch stays healthy\nC) Storing desired cluster state only in a wiki page\nD) Manual weekly builds by one release manager",
      "Correct: B — CI is frequent automated build/test on changes. A is closer to reckless continuous deployment. C is not CI. D is the opposite of CI.",
      "Phát biểu nào mô tả đúng nhất Continuous Integration (CI)?",
      "A) Tự deploy mọi commit lên production không cần test\nB) Tự động build và test mỗi thay đổi để nhánh chung luôn khỏe\nC) Chỉ lưu trạng thái cluster mong muốn trên wiki\nD) Build thủ công hàng tuần bởi một release manager",
      "Đáp án đúng: B — CI = build/test tự động thường xuyên. A gần với deploy liên tục thiếu kiểm soát. C không phải CI. D trái với CI.",
      "If you see 'no tests' with 'CI', eliminate it."),
    M("sec-tips", "MCQ: Docker vs VM", "Theory",
      "Compared with a traditional VM, a container typically:",
      "A) Boots a full guest OS kernel for every app instance\nB) Shares the host kernel and packages the app with its userspace dependencies\nC) Cannot be versioned as an image\nD) Removes the need for any process isolation",
      "Correct: B — containers share the host kernel; images package app + deps. A describes VMs. C/D are false.",
      "So với VM truyền thống, container thường:",
      "A) Boot full guest OS kernel cho mỗi instance app\nB) Dùng chung kernel host và đóng gói app kèm dependency userspace\nC) Không thể version dưới dạng image\nD) Không cần bất kỳ cô lập process nào",
      "Đáp án đúng: B — container share kernel host; image chứa app + deps. A là VM. C/D sai.",
      "Don't pick 'containers need no isolation' — namespaces/cgroups still isolate."),
    M("sec-tips", "MCQ: K8s readiness probe", "Applied",
      "A Deployment serves traffic via a Service. Pods start but users still get errors for ~30s. Which probe mainly controls when a Pod receives traffic?",
      "A) livenessProbe\nB) readinessProbe\nC) startupProbe only, forever\nD) No probe — Services always wait for perfect app health automatically",
      "Correct: B — readiness gates endpoints. Liveness restarts unhealthy containers. Startup helps slow boots but readiness decides traffic.",
      "Deployment nhận traffic qua Service. Pod đã start nhưng user vẫn lỗi ~30s. Probe nào chủ yếu quyết định Pod nhận traffic?",
      "A) livenessProbe\nB) readinessProbe\nC) chỉ startupProbe mãi mãi\nD) Không cần probe — Service tự chờ app khỏe hoàn hảo",
      "Đáp án đúng: B — readiness quyết định endpoint nhận traffic. Liveness restart khi unhealthy. Startup hỗ trợ boot chậm nhưng traffic vẫn do readiness.",
      "Confusing liveness with readiness is a classic exam trap."),
    M("sec-tips", "MCQ: broken pipeline first step", "Situation",
      "Jenkins/GitLab CI fails on the 'test' stage after a merge. What is the best first action?",
      "A) Force-push to main to skip the stage\nB) Read the failed job logs, reproduce locally or re-run with more verbosity, identify whether code/tests/env/credentials broke\nC) Delete the Jenkins agent immediately\nD) Disable all quality gates permanently",
      "Correct: B — evidence first. A/D destroy safety. C is random without diagnosis.",
      "CI fail ở stage 'test' sau merge. Hành động đầu tiên tốt nhất là gì?",
      "A) Force-push main để bỏ stage\nB) Đọc log job fail, reproduce/local hoặc chạy lại verbose, xác định lỗi do code/test/env/credential\nC) Xóa agent Jenkins ngay\nD) Tắt vĩnh viễn mọi quality gate",
      "Đáp án đúng: B — bằng chứng trước. A/D phá an toàn. C là hành động mù.",
      "Any option that skips logs/evidence is usually wrong."),
    M("sec-tips", "MCQ: secrets in Git", "Security / ATTT",
      "Where should production database passwords live for a CI/CD pipeline?",
      "A) Hard-coded in the Jenkinsfile committed to the app repo\nB) In a secrets manager / CI protected variables / sealed secrets — injected at runtime, least privilege\nC) In a public README for 'team convenience'\nD) In the Docker image ENV baked forever with no rotation",
      "Correct: B — vault/CI protected vars/K8s secrets with access control and rotation. A/C/D leak or freeze secrets.",
      "Mật khẩu DB production cho pipeline CI/CD nên nằm ở đâu?",
      "A) Hard-code trong Jenkinsfile commit vào repo app\nB) Secrets manager / biến CI protected / sealed secrets — inject lúc chạy, least privilege\nC) Để trong README public cho tiện\nD) Bake vào ENV image Docker mãi không xoay vòng",
      "Đáp án đúng: B — vault/biến CI protected/K8s secret có phân quyền và rotation. A/C/D lộ hoặc đóng băng secret.",
      "VNPT JD stresses ATTT collaboration — never normalize secrets in Git."),
    M("sec-tips", "MCQ: Prometheus vs ELK", "Applied monitoring",
      "You need to know CPU usage trend of a service over 7 days and alert when error rate spikes. Which pairing fits best?",
      "A) ELK only for both metrics and alerts (no time-series DB)\nB) Prometheus for metrics/alerts + Grafana dashboards; ELK for log search/correlation\nC) Ansible for metrics storage\nD) Only screenshots in chat — no tooling",
      "Correct: B — Prometheus/Grafana for metrics/alerts; ELK for logs. Complementary, not duplicates of each other.",
      "Cần xu hướng CPU 7 ngày và alert khi error rate tăng. Cặp công cụ nào hợp nhất?",
      "A) Chỉ ELK cho cả metric và alert (không time-series DB)\nB) Prometheus cho metric/alert + Grafana dashboard; ELK để tìm/tương quan log\nC) Ansible để lưu metrics\nD) Chỉ chụp màn hình gửi chat",
      "Đáp án đúng: B — Prometheus/Grafana cho metric/alert; ELK cho log. Bổ sung nhau.",
      "Don't treat ELK as a full metrics TSDB replacement in exam answers."),
    M("sec-tips", "MCQ: RPO vs RTO", "Backup theory",
      "RPO (Recovery Point Objective) primarily means:",
      "A) Maximum acceptable time to restore service after an outage\nB) Maximum acceptable data loss measured in time (how far back backups must cover)\nC) Number of Kubernetes replicas\nD) CPU quota of a namespace",
      "Correct: B — RPO = how much data you can lose. RTO = how fast you must be back. A is RTO.",
      "RPO (Recovery Point Objective) chủ yếu nghĩa là:",
      "A) Thời gian tối đa chấp nhận được để khôi phục dịch vụ sau sự cố\nB) Lượng mất dữ liệu tối đa chấp nhận được (theo thời gian) — backup phải phủ xa bao nhiêu\nC) Số replica Kubernetes\nD) CPU quota của namespace",
      "Đáp án đúng: B — RPO = mất dữ liệu bao nhiêu. RTO = phục hồi nhanh thế nào. A là RTO.",
      "Swap RPO/RTO is one of the most common MCQ traps."),
    M("sec-tips", "MCQ: alert storm response", "Situation",
      "On-call receives 200 similar alerts in 10 minutes after a bad deploy. Best immediate approach?",
      "A) Ignore all alerts until morning\nB) Mitigate impact (rollback/scale/feature flag), silence or group duplicate noise carefully, then diagnose root cause with metrics/logs\nC) Turn off Prometheus forever\nD) Restart every node in the company without checking blast radius",
      "Correct: B — stop the bleeding, reduce noise intentionally, then root-cause. A/C/D are reckless.",
      "On-call nhận 200 alert giống nhau trong 10 phút sau deploy xấu. Cách xử lý ngay tốt nhất?",
      "A) Bỏ qua tất cả đến sáng\nB) Giảm hại (rollback/scale/feature flag), silence/gộp nhiễu cẩn thận, rồi chẩn đoán gốc bằng metric/log\nC) Tắt Prometheus mãi mãi\nD) Restart mọi node không xét blast radius",
      "Đáp án đúng: B — cầm máu, giảm nhiễu có chủ đích, rồi root-cause. A/C/D liều lĩnh.",
      "Good situational answers prioritize users first, then signal quality, then root cause."),
    M("sec-tips", "MCQ: Linux permissions", "Theory",
      "File mode 640 means:",
      "A) Owner rwx, group rwx, others rwx\nB) Owner rw-, group r--, others ---\nC) Owner r-x, group r-x, others r-x\nD) Sticky bit only",
      "Correct: B — 6=rw-, 4=r--, 0=---.",
      "Mode file 640 nghĩa là:",
      "A) Owner rwx, group rwx, others rwx\nB) Owner rw-, group r--, others ---\nC) Owner r-x, group r-x, others r-x\nD) Chỉ sticky bit",
      "Đáp án đúng: B — 6=rw-, 4=r--, 0=---.",
      "Memorize 4=r, 2=w, 1=x for octal drills."),
    M("sec-tips", "MCQ: idempotent Ansible", "Applied automation",
      "What does 'idempotent' mean for an Ansible task?",
      "A) Running it twice always doubles the number of packages installed\nB) Re-running it converges to the same desired state without unnecessary changes\nC) It can only run on Windows\nD) It ignores errors forever",
      "Correct: B — safe re-run to desired state. A is the opposite. C/D false.",
      "'Idempotent' với task Ansible nghĩa là gì?",
      "A) Chạy hai lần luôn nhân đôi số package cài\nB) Chạy lại sẽ về cùng trạng thái mong muốn, không đổi lung tung không cần thiết\nC) Chỉ chạy trên Windows\nD) Bỏ qua lỗi mãi mãi",
      "Đáp án đúng: B — chạy lại an toàn về desired state. A trái nghĩa. C/D sai.",
      "If an option implies 'run once only forever', it's usually not idempotency."),
    M("sec-tips", "MCQ: Nginx reverse proxy", "Applied",
      "Nginx terminates TLS and forwards HTTP to an app on 127.0.0.1:8080. This pattern is mainly called:",
      "A) Reverse proxy / TLS termination at the edge\nB) DNS poisoning\nC) GitOps reconciliation\nD) Horizontal Pod Autoscaler",
      "Correct: A — classic edge reverse proxy. Others are unrelated concepts.",
      "Nginx kết thúc TLS và forward HTTP tới app 127.0.0.1:8080. Pattern này chủ yếu gọi là:",
      "A) Reverse proxy / TLS termination ở edge\nB) DNS poisoning\nC) GitOps reconciliation\nD) Horizontal Pod Autoscaler",
      "Đáp án đúng: A — reverse proxy edge cổ điển. Các lựa chọn khác không liên quan.",
      "Don't overfit K8s terms onto plain Nginx questions."),
    M("sec-tips", "MCQ: process vs thread", "OS fundamentals",
      "Which statement is most accurate?",
      "A) Threads in the same process always have completely separate address spaces like different VMs\nB) A process has its own address space; threads in a process share memory space but have separate stacks/registers\nC) Sockets can only exist without processes\nD) Virtualization means deleting the filesystem",
      "Correct: B — classic OS model. A confuses threads with processes/VMs.",
      "Phát biểu nào đúng nhất?",
      "A) Thread trong cùng process luôn có không gian địa chỉ tách hoàn toàn như các VM khác nhau\nB) Process có address space riêng; các thread trong process chia sẻ bộ nhớ nhưng có stack/register riêng\nC) Socket chỉ tồn tại khi không có process\nD) Virtualization nghĩa là xóa filesystem",
      "Đáp án đúng: B — mô hình OS cổ điển. A nhầm thread với process/VM.",
      "JD explicitly lists process/threads/concurrency — expect definition MCQs."),
]
