# Card data: real experience step-by-step (PRIMARY). Synthetic study content only.
# Intended importer (future regenerator): from cards_experience import CARDS
# Shape: {sec, kind, title, sub, c_en, m_en, c_vi, m_vi, crib?, note?} — no date fields.
# Honesty: Akktis full-stack+DevOps (Linux SSH, CI/CD multi-env mobile+web, GCP Cloud Run/SQL/Storage,
# LiteSpeed/Apache, docs/hardening) + IELTS AI Tutor (RN/TS iOS/Android, Cloud Run, store publish).


def C(sec, title, sub, c_en, m_en, c_vi, m_vi, crib="", note=""):
    return {"sec": sec, "kind": "concept", "title": title, "sub": sub,
            "c_en": c_en, "m_en": m_en, "c_vi": c_vi, "m_vi": m_vi,
            "crib": crib, "note": note}


def S(sec, title, sub, c_en, m_en, c_vi, m_vi, crib="", note=""):
    """Step card — same shape as concept; use for numbered procedures."""
    return C(sec, title, sub, c_en, m_en, c_vi, m_vi, crib, note)


CARDS = [
    # ── sec-overview ──────────────────────────────────────────────────────────
    C("sec-overview", "How I describe my DevOps experience", "Honest one-breath summary",
      "I'm a full-stack engineer who also owns delivery and ops: Linux servers over SSH, CI/CD for mobile and web across environments, and GCP services — Cloud Run, Cloud SQL, and Storage. At Akktis that mix is day-to-day; with IELTS AI Tutor I shipped a React Native app to both stores with a Cloud Run backend.",
      "Lead with what I operate (pipeline → deploy → logs → fix), not buzzword lists. Spine = Cloud Build / CI runners + Cloud Run + Linux VM + mobile release — not deep Kubernetes HA or Jenkins-only expertise.",
      "Tôi là full-stack kiêm delivery/ops: Linux qua SSH, CI/CD mobile+web multi-env, và GCP — Cloud Run, Cloud SQL, Storage. Ở Akktis đó là việc hằng ngày; với IELTS AI Tutor tôi ship app React Native lên cả hai store kèm backend Cloud Run.",
      "Lead bằng việc tôi operate (pipeline → deploy → log → fix), không liệt kê buzzword. Spine = Cloud Build/CI runner + Cloud Run + Linux VM + mobile release — không claim sâu Kubernetes HA hay chỉ chuyên Jenkins.",
      "Don't invent cluster/HA claims. Prefer 'I operate Cloud Run and VMs' over 'I run enterprise K8s platforms'."),

    C("sec-overview", "Akktis vs IELTS — what each proves", "Two complementary stories",
      "Akktis: client web/mobile delivery — Ubuntu/Debian SSH, multi-env CI/CD, LiteSpeed/Apache for PHP/CMS apps, GCP Cloud Run/SQL/Storage, docs and basic hardening with a France-based remote team. IELTS AI Tutor: end-to-end product ownership — React Native/TypeScript iOS+Android, Cloud Run API, published on Google Play and App Store.",
      "Use Akktis for ops breadth (VM, web server, multi-env). Use IELTS for mobile CI + store release + Cloud Run backend ownership.",
      "Akktis: delivery web/mobile cho client — SSH Ubuntu/Debian, CI/CD multi-env, LiteSpeed/Apache cho app PHP/CMS, GCP Cloud Run/SQL/Storage, docs và harden cơ bản với team Pháp remote. IELTS AI Tutor: ownership end-to-end — React Native/TypeScript iOS+Android, API Cloud Run, đã publish lên Google Play và App Store.",
      "Dùng Akktis cho ops breadth (VM, web server, multi-env). Dùng IELTS cho mobile CI + store release + ownership backend Cloud Run.",
      "Don't merge projects into one fake mega-platform. Keep stories separate when asked."),

    C("sec-overview", "My DevOps stack map", "Tools I can defend in interview",
      "Source: Git. CI: Cloud Build and/or generic CI runners that build on push/tag. Artifacts: container images in Artifact Registry; mobile AAB/IPA to storage or store tracks. Runtime: Cloud Run for container APIs; Linux VMs with LiteSpeed/Apache/Nginx for classic web. Data: Cloud SQL + Cloud Storage. Ops: SSH, logs, revisions, env promotion, docs.",
      "I can walk commit → build → artifact → deploy → verify. I stay honest if a specific vendor plugin name isn't what we used — I describe the stage and why it exists.",
      "Source: Git. CI: Cloud Build và/hoặc CI runner generic build theo push/tag. Artifact: image trong Artifact Registry; AAB/IPA mobile lên storage hoặc store track. Runtime: Cloud Run cho API container; VM Linux với LiteSpeed/Apache/Nginx cho classic web. Data: Cloud SQL + Cloud Storage. Ops: SSH, log, revision, promote env, docs.",
      "Tôi walk được commit → build → artifact → deploy → verify. Trung thực nếu tên plugin cụ thể không phải tool đã dùng — mô tả stage và lý do tồn tại.",
      "Listing Jenkins/K8s/ELK because a JD mentions them, without mapping to my real path, weakens credibility."),

    C("sec-overview", "How I talk under pressure", "Evidence-first habits",
      "When something breaks I isolate layer: recent change → CI log → runtime log/revision → env/secret → network/DB. I mitigate first (rollback revision, revert commit, free disk), then fix root cause and update the checklist/docs so the gap doesn't repeat.",
      "Spoken habit: what changed, what failed, what I verified, what I changed next. Same pattern for mobile build fail, Cloud Run 5xx, or VM disk full.",
      "Khi break tôi isolate layer: change gần đây → CI log → runtime log/revision → env/secret → network/DB. Mitigate trước (rollback revision, revert commit, free disk), rồi fix root cause và update checklist/docs.",
      "Habit khi nói: đổi gì, fail gì, verify gì, fix gì tiếp. Cùng pattern cho mobile build fail, Cloud Run 5xx, hay VM full disk.",
      "Guessing 'maybe DNS' without checking deploy/logs first is a trap."),

    # ── sec-mobile-cicd ───────────────────────────────────────────────────────
    S("sec-mobile-cicd", "Goal: Android & iOS CI/CD", "What success looks like",
      "Goal: every meaningful branch/tag produces a reproducible mobile build artifact (Android AAB/APK, iOS IPA concepts), with secrets/signing kept out of Git, and a clear path to Play/App Store distribution tracks — not a fragile laptop-only release.",
      "1) Define which Git events trigger a build (PR, main, release tag).\n2) Separate build vs distribute stages.\n3) Keep signing material in CI secret store.\n4) Store artifacts and notify on fail/success.\n5) Promote by environment (dev/staging/prod-like).",
      "Mục tiêu: mỗi branch/tag quan trọng tạo artifact mobile reproducible (AAB/APK Android, khái niệm IPA iOS), secret/signing ngoài Git, path rõ tới track Google Play/App Store — không release chỉ trên laptop.",
      "1) Define event Git nào trigger build (PR, main, release tag).\n2) Tách stage build vs distribute.\n3) Giữ signing trong secret store của CI.\n4) Lưu artifact và notify khi fail/success.\n5) Promote theo env (dev/staging/prod-like).",
      "Don't claim a specific third-party mobile CI brand if you only used Cloud Build / generic runners — describe stages."),

    S("sec-mobile-cicd", "Repo layout & trigger model", "What fires the pipeline",
      "React Native / TypeScript monorepo or app repo: mobile app code, backend may be separate. Triggers usually: push to main → staging build; release tag / manual approval → store-bound build. Cloud Build trigger or CI webhook watches the branch/tag.",
      "1) Map branches to envs (feature → CI check; develop/main → internal build; tag vX.Y.Z → release candidate).\n2) Configure trigger on push/tag in Cloud Build or equivalent.\n3) Checkout with full history if version/git describe needed.\n4) Fail fast on lint/test before expensive native builds when possible.",
      "Repo React Native/TypeScript (hoặc monorepo): code mobile; backend có thể tách. Trigger thường: push main → build staging; tag release / approval → build lên store. Cloud Build trigger hoặc webhook CI watch branch/tag.",
      "1) Map branch → env (feature → CI check; develop/main → internal build; tag vX.Y.Z → release candidate).\n2) Config trigger push/tag trên Cloud Build hoặc tương đương.\n3) Checkout đủ history nếu cần version/git describe.\n4) Fail-fast ở lint/test trước native build đắt khi được.",
      "One pipeline for every branch without caching can burn quota — know what you trigger and why.",
      "gcloud builds triggers create github --name=mobile-main --branch-pattern='^main$' --build-config=cloudbuild.mobile.yaml\n# or: push tag v* → release pipeline"),

    S("sec-mobile-cicd", "Secrets & signing (honest flow)", "Keys never live in Git",
      "Typical flow (concepts, not inventing a private plugin name): Android keystore + key passwords in Secret Manager / CI encrypted vars; iOS distribution certificate + provisioning profile injected into the macOS build agent at runtime. Store API keys (Play Console / App Store Connect) stay in secrets for upload steps.",
      "1) Create keystore / certs offline once; never commit them.\n2) Upload to Secret Manager or CI secret store.\n3) Pipeline mounts/decrypts only during the signing stage.\n4) Restrict IAM/who can read secrets.\n5) Rotate when people leave or leakage suspected.",
      "Flow điển hình (khái niệm): Android keystore + password trong Secret Manager / biến encrypt của CI; iOS distribution cert + provisioning profile inject vào agent macOS lúc runtime. Store API key (Play / App Store Connect) cũng nằm trong secret cho bước upload.",
      "1) Tạo keystore/cert offline một lần; không commit.\n2) Upload vào Secret Manager hoặc secret store CI.\n3) Pipeline chỉ mount/decrypt trong signing stage.\n4) Restrict IAM/ai được đọc secret.\n5) Rotate khi người rời team hoặc nghi leak.",
      "Saying 'signing is automatic' without knowing where the keystore/profile lives fails follow-ups."),

    S("sec-mobile-cicd", "Build Android AAB/APK", "Gradle / RN release steps",
      "Android release path for a React Native app: install JS deps, generate native Android project artifacts if needed, run Gradle assembleRelease or bundleRelease to produce APK/AAB, sign with the release keystore, then upload artifact.",
      "1) npm/yarn/pnpm install (lockfile).\n2) Set ANDROID_HOME / accept SDK licenses on the builder.\n3) Inject keystore path + passwords from secrets into gradle.properties or env.\n4) ./gradlew bundleRelease (AAB for Play) or assembleRelease (APK for sideload/testing).\n5) Copy outputs/bundle/release/*.aab to artifact storage.",
      "Release path Android cho app React Native: install JS deps, chuẩn bị native Android, chạy Gradle assembleRelease/bundleRelease ra APK/AAB, sign bằng release keystore, rồi upload artifact.",
      "1) npm/yarn/pnpm install (lockfile).\n2) Set ANDROID_HOME / accept SDK license trên builder.\n3) Inject keystore path + password từ secret vào gradle.properties hoặc env.\n4) ./gradlew bundleRelease (AAB cho Play) hoặc assembleRelease (APK test).\n5) Copy outputs/bundle/release/*.aab lên artifact storage.",
      "APK vs AAB: Play prefers AAB. Don't claim you upload unsigned APKs to production tracks.",
      "cd android && ./gradlew bundleRelease\n# outputs: app/build/outputs/bundle/release/app-release.aab\ngcloud builds submit --config=cloudbuild.android.yaml ."),

    S("sec-mobile-cicd", "Build iOS IPA (concepts)", "Certs, profiles, archive",
      "iOS CI needs a macOS runner. Conceptually: install deps, select Xcode, install distribution certificate + provisioning profile into the keychain, archive the app, export IPA for App Store or ad-hoc. React Native uses the ios/ Xcode workspace.",
      "1) Use a macOS CI image/agent.\n2) Install CocoaPods if the project uses Pods (pod install).\n3) Import signing cert + profile from secrets into temporary keychain.\n4) xcodebuild archive → exportOptions.plist → IPA.\n5) Never leave certs on a shared machine after the job.",
      "CI iOS cần runner macOS. Khái niệm: install deps, chọn Xcode, install distribution cert + provisioning profile vào keychain, archive app, export IPA cho App Store hoặc ad-hoc. React Native dùng workspace trong ios/.",
      "1) Dùng image/agent macOS.\n2) pod install nếu project dùng CocoaPods.\n3) Import cert + profile từ secret vào keychain tạm.\n4) xcodebuild archive → exportOptions.plist → IPA.\n5) Không để cert trên máy shared sau job.",
      "If asked exact Fastlane lane names you didn't use: say you know the stages (match/signing → gym/archive → deliver/upload) without inventing project-specific lanes.",
      "# conceptual\nxcodebuild -workspace ios/App.xcworkspace -scheme App -configuration Release archive -archivePath build/App.xcarchive\nxcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build/ipa -exportOptionsPlist ExportOptions.plist"),

    S("sec-mobile-cicd", "Artifact storage & store upload", "Where builds go",
      "After a green build: store AAB/IPA in Cloud Storage (or CI artifact store) with versioned object names. Distribution: upload to Google Play internal/closed testing track and App Store Connect TestFlight / App Store — using store credentials from secrets. Store publish for IELTS AI Tutor proves this path exists end-to-end.",
      "1) Name artifacts with git tag/sha + platform.\n2) Upload to gs://…/releases/…\n3) Optional: promote to Play/App Store tracks (internal first).\n4) Record build number ↔ commit in release notes.\n5) Keep retention policy so disks/buckets don't fill forever.",
      "Sau green build: lưu AAB/IPA trên Cloud Storage (hoặc artifact CI) với tên có version. Distribute: upload track internal Google Play và TestFlight/App Store — dùng store credential từ secret. IELTS AI Tutor đã lên store chứng minh path này end-to-end.",
      "1) Đặt tên artifact theo tag/sha + platform.\n2) Upload gs://…/releases/…\n3) Optional: promote lên track Play/App Store (internal trước).\n4) Ghi build number ↔ commit trong release notes.\n5) Retention để bucket không phình mãi.",
      "Don't claim you pressed 'publish to production' every time if you mainly built and handed off to a store review step — say your real ownership.",
      "gsutil cp app-release.aab gs://my-mobile-artifacts/$TAG/\n# Play/App Store upload via official CLI or CI marketplace action — credentials from Secret Manager"),

    S("sec-mobile-cicd", "Notify & fail handling", "Humans get signal, not noise",
      "Pipeline should notify on failure with the failing stage link, and on success with artifact path / store track. Fail fast on signing errors (wrong password, expired profile) so you don't burn 20 minutes of compile before discovering secrets are bad.",
      "1) Surface first red stage log URL in chat/email.\n2) Distinguish flaky network vs deterministic compile/sign errors.\n3) Block release tag promotion if smoke checks fail.\n4) On secret/expiry failures, rotate then re-run — don't disable signing checks.\n5) Keep a short runbook: common mobile CI failures.",
      "Pipeline nên notify khi fail kèm link stage, và khi success kèm artifact path/track. Fail-fast ở lỗi signing (sai password, profile hết hạn) để không burn 20 phút compile rồi mới biết secret hỏng.",
      "1) Đưa URL log stage đỏ đầu tiên vào chat/email.\n2) Phân biệt network flaky vs lỗi compile/sign deterministic.\n3) Block promote tag release nếu smoke fail.\n4) Lỗi secret/expiry → rotate rồi re-run — không tắt signing check.\n5) Giữ runbook ngắn: lỗi mobile CI thường gặp.",
      "Mute-all notifications is as bad as page-on-every-warning."),

    S("sec-mobile-cicd", "Multi-env mobile builds", "Dev / staging / prod-like",
      "Same codebase, different env configs: API base URL, feature flags, bundle IDs / applicationId suffixes, and which signing identity is used. Staging builds may use different Firebase/backend endpoints than production. Promotion means a new tagged build with prod config — not editing a live binary by hand.",
      "1) Externalize env via .env / build flavors / XCConfig — not hardcoded prod URLs in main.\n2) Map CI job matrix or substitutions per env.\n3) Never reuse prod keystore for debug curiosity on shared laptops carelessly.\n4) Verify staging app hits staging Cloud Run before tagging prod.\n5) Document which track receives which env.",
      "Cùng codebase, khác config env: API base URL, feature flag, suffix bundle ID / applicationId, và signing identity nào. Build staging có thể trỏ backend khác production. Promote = build tag mới với config prod — không sửa binary tay.",
      "1) Tách env bằng .env / flavor / XCConfig — không hardcode URL prod trong main.\n2) Map job matrix hoặc substitutions CI theo env.\n3) Không dùng bừa prod keystore cho debug trên laptop shared.\n4) Verify app staging hit đúng Cloud Run staging trước khi tag prod.\n5) Document track nào nhận env nào.",
      "Staging green ≠ prod safe if env vars and signing differ — always call out the delta."),

    S("sec-mobile-cicd", "Troubleshoot failed mobile builds", "Systematic debug",
      "Failed mobile CI: read the first error, not the last noise. Common buckets: dependency/lockfile drift, SDK/Xcode version mismatch, signing/profile expired, OOM on Gradle, wrong working directory, missing secret. Reproduce locally with the same Node/JDK/Xcode when possible.",
      "1) Open failing step log; copy the first ERROR.\n2) Check what changed since last green (deps, native module, CI image).\n3) Validate secrets still decrypt / profiles not expired.\n4) Reproduce: same Node + JDK; cd android && ./gradlew … or xcodebuild.\n5) Fix forward (pin version, renew profile) or revert; re-run; note in changelog.",
      "Mobile CI fail: đọc error đầu, không đọc noise cuối. Bucket thường gặp: lệch lockfile/deps, lệch SDK/Xcode, signing/profile hết hạn, OOM Gradle, sai working directory, thiếu secret. Reproduce local cùng Node/JDK/Xcode nếu được.",
      "1) Mở log bước fail; copy ERROR đầu tiên.\n2) Xem đổi gì từ last green (deps, native module, CI image).\n3) Validate secret còn decrypt / profile còn hạn.\n4) Reproduce: cùng Node + JDK; cd android && ./gradlew … hoặc xcodebuild.\n5) Fix forward (pin version, renew profile) hoặc revert; re-run; ghi changelog.",
      "Re-running without reading the log wastes quota and credibility.",
      "# Android OOM hint\n./gradlew bundleRelease --no-daemon\n# Check keystore\nkeytool -list -v -keystore release.keystore"),

    S("sec-mobile-cicd", "Interview story: IELTS store release", "Spoken bridge card",
      "IELTS AI Tutor is the concrete proof: React Native/TypeScript app for iOS and Android, backend on Cloud Run, published on Google Play and App Store. In interview I describe CI as automating build + signing + artifact, then store upload/review — I stay precise about which steps I owned versus store review waiting time.",
      "1) Say product + platforms.\n2) Say CI builds native artifacts from Git.\n3) Say secrets/signing stay out of Git.\n4) Say backend is Cloud Run (separate deploy path).\n5) Say stores are live — ops continues after publish.",
      "IELTS AI Tutor là bằng chứng cụ thể: app React Native/TypeScript iOS+Android, backend Cloud Run, đã publish lên Google Play và App Store. Khi interview tôi mô tả CI automate build + signing + artifact, rồi store upload/review — nói rõ bước mình own versus thời gian chờ review.",
      "1) Nói product + platform.\n2) Nói CI build artifact native từ Git.\n3) Nói secret/signing ngoài Git.\n4) Nói backend là Cloud Run (deploy path riêng).\n5) Nói store đã live — ops tiếp tục sau publish.",
      "Don't invent download counts or revenue. Qualitative: published and operated."),

    # ── sec-cloudrun ──────────────────────────────────────────────────────────
    S("sec-cloudrun", "Goal: Cloud Run + Cloud Build CI/CD", "Serverless containers on GCP",
      "Goal: every push (or tag) builds a container image, stores it in Artifact Registry, deploys a new Cloud Run revision with the right env/secrets, and can roll back. This is the spine for IELTS backend and Akktis cloud services — not a claim of managing GKE node pools.",
      "1) Dockerfile that runs the API process.\n2) Build → push image.\n3) Deploy Cloud Run service.\n4) Wire env, secrets, Cloud SQL.\n5) Automate with Cloud Build trigger + cloudbuild.yaml.",
      "Mục tiêu: mỗi push (hoặc tag) build container image, lưu Artifact Registry, deploy revision Cloud Run mới với env/secret đúng, và rollback được. Đây là spine cho backend IELTS và cloud service Akktis — không claim quản lý GKE node pool.",
      "1) Dockerfile chạy process API.\n2) Build → push image.\n3) Deploy service Cloud Run.\n4) Wire env, secret, Cloud SQL.\n5) Automate bằng Cloud Build trigger + cloudbuild.yaml.",
      "Cloud Run ≠ SSH server. No persistent local disk assumptions."),

    S("sec-cloudrun", "Dockerfile → runnable image", "Package the API",
      "Containerize the backend: choose a slim base, install deps, copy app, expose the port Cloud Run expects (container must listen on $PORT). Prefer non-root user when practical. Keep secrets out of the image layers.",
      "1) FROM language runtime slim image.\n2) Copy lockfiles → install deps (layer cache).\n3) Copy source; set WORKDIR.\n4) EXPOSE and CMD/ENTRYPOINT listening on 8080 or $PORT.\n5) .dockerignore node_modules/.git to keep images small.",
      "Containerize backend: base slim, install deps, copy app, listen đúng $PORT Cloud Run. Ưu tiên non-root khi hợp lý. Không nhét secret vào image layer.",
      "1) FROM image runtime slim.\n2) Copy lockfile → install deps (layer cache).\n3) Copy source; set WORKDIR.\n4) EXPOSE và CMD/ENTRYPOINT listen 8080 hoặc $PORT.\n5) .dockerignore node_modules/.git để image nhỏ.",
      "Baking .env with production passwords into the image is a hard fail in interviews.",
      "docker build -t api:local .\ndocker run --rm -p 8080:8080 -e PORT=8080 api:local"),

    S("sec-cloudrun", "Build & push to Artifact Registry", "Named, versioned images",
      "Tag images with project/region Artifact Registry path and git sha or build id. Cloud Build can run docker build + docker push, or use kaniko/buildpacks. Humans shouldn't docker push from laptops as the only prod path.",
      "1) Create Artifact Registry Docker repo.\n2) Authenticate docker to the registry.\n3) Build with tag REGION-docker.pkg.dev/PROJECT/REPO/SERVICE:$SHORT_SHA.\n4) Push tag; optionally also push :latest for non-prod.\n5) Deploy by digest/tag immutably when possible.",
      "Tag image theo path Artifact Registry region/project và git sha hoặc build id. Cloud Build chạy docker build + push (hoặc kaniko/buildpacks). Không lấy docker push từ laptop làm prod path duy nhất.",
      "1) Tạo Artifact Registry Docker repo.\n2) Auth docker với registry.\n3) Build tag REGION-docker.pkg.dev/PROJECT/REPO/SERVICE:$SHORT_SHA.\n4) Push tag; có thể thêm :latest cho non-prod.\n5) Deploy theo digest/tag immutable khi được.",
      ":latest in production without digest tracking makes rollbacks fuzzy.",
      "gcloud artifacts repositories create apps --repository-format=docker --location=asia-southeast1\ngcloud auth configure-docker asia-southeast1-docker.pkg.dev\ndocker tag api:local asia-southeast1-docker.pkg.dev/$PROJECT/apps/api:$SHORT_SHA\ndocker push asia-southeast1-docker.pkg.dev/$PROJECT/apps/api:$SHORT_SHA"),

    S("sec-cloudrun", "Deploy Cloud Run service", "First service & later revisions",
      "gcloud run deploy creates/updates a service: image, region, allow/unauth, CPU/memory, concurrency, min/max instances. Each deploy creates a revision. Traffic can point 100% at the new revision or split for canary.",
      "1) Pick region close to users/SQL.\n2) gcloud run deploy SERVICE --image=… --region=…\n3) Set --memory/--cpu/--max-instances appropriate to load.\n4) Decide ingress (all / internal).\n5) Verify URL returns healthy response.",
      "gcloud run deploy tạo/update service: image, region, auth, CPU/memory, concurrency, min/max instances. Mỗi deploy tạo revision. Traffic có thể 100% revision mới hoặc split canary.",
      "1) Chọn region gần user/SQL.\n2) gcloud run deploy SERVICE --image=… --region=…\n3) Set --memory/--cpu/--max-instances phù hợp load.\n4) Quyết định ingress (all / internal).\n5) Verify URL trả healthy response.",
      "min-instances=0 saves money but allows cold starts — say the tradeoff out loud.",
      "gcloud run deploy ielts-api --image=asia-southeast1-docker.pkg.dev/$PROJECT/apps/api:$SHORT_SHA --region=asia-southeast1 --allow-unauthenticated\n# tighten auth in real prod when appropriate"),

    S("sec-cloudrun", "Env vars & secrets on Cloud Run", "Config outside the image",
      "Runtime config: plain env for non-secret settings; Secret Manager references for DB passwords/API keys. Mount or inject at revision level so rotating a secret doesn't require rebuilding the image — only a new revision or secret version.",
      "1) List required env keys per environment.\n2) Put secrets in Secret Manager.\n3) Grant the Cloud Run service account secretAccessor.\n4) Attach secrets/env on deploy or via console/YAML.\n5) Never log secret values.",
      "Config runtime: plain env cho non-secret setting; Secret Manager cho DB password/API key. Inject ở revision để rotate secret không cần rebuild image — chỉ revision mới hoặc secret version.",
      "1) List env key theo env.\n2) Đưa secret vào Secret Manager.\n3) Grant service account Cloud Run quyền secretAccessor.\n4) Attach secret/env lúc deploy hoặc YAML.\n5) Không log giá trị secret.",
      "Copy-pasting prod secrets into staging 'just to test' creates lasting risk.",
      "gcloud run services update ielts-api --region=asia-southeast1 \\\n  --set-env-vars=NODE_ENV=production \\\n  --set-secrets=DB_PASSWORD=db-pass:latest"),

    S("sec-cloudrun", "Cloud SQL connectivity concept", "Private path, not public guesswork",
      "Cloud Run reaches Cloud SQL typically via the Cloud SQL Auth Proxy / Unix socket connector built into Cloud Run, or private IP / Serverless VPC Access depending on setup. The app uses a connection string that matches the connector; IAM and DB user still apply.",
      "1) Create Cloud SQL instance; note connection name PROJECT:REGION:INSTANCE.\n2) Enable Cloud SQL connection on the Cloud Run service.\n3) Use least-privilege DB user.\n4) Store password in Secret Manager.\n5) Test with a /health that checks DB ping without exposing data.",
      "Cloud Run tới Cloud SQL thường qua Cloud SQL Auth Proxy / Unix socket connector tích hợp Cloud Run, hoặc private IP / Serverless VPC Access tùy setup. App dùng connection string khớp connector; IAM và DB user vẫn apply.",
      "1) Tạo instance Cloud SQL; ghi connection name PROJECT:REGION:INSTANCE.\n2) Enable Cloud SQL connection trên service Cloud Run.\n3) Dùng DB user least privilege.\n4) Password trong Secret Manager.\n5) Test /health ping DB mà không lộ data.",
      "Opening Cloud SQL to 0.0.0.0/0 'temporarily' is a classic interview trap — say you wouldn't.",
      "gcloud run services update ielts-api --region=asia-southeast1 \\\n  --add-cloudsql-instances=$PROJECT:$REGION:$INSTANCE"),

    S("sec-cloudrun", "Cloud Build trigger on push", "Git → automatic deploy",
      "Connect the repo; create a trigger on branch (e.g. main) or tag. Trigger runs cloudbuild.yaml with substitutions like SHORT_SHA. Service account for Cloud Build needs permission to push Artifact Registry and deploy Cloud Run.",
      "1) Connect GitHub/GitLab/Cloud Source to Cloud Build.\n2) Create trigger: branch main → cloudbuild.yaml.\n3) Grant Cloud Build SA: artifact registry writer + run admin (or narrower custom).\n4) Push a commit; watch build in console.\n5) Confirm new Cloud Run revision appeared.",
      "Connect repo; tạo trigger theo branch (vd main) hoặc tag. Trigger chạy cloudbuild.yaml với substitution như SHORT_SHA. Service account Cloud Build cần quyền push Artifact Registry và deploy Cloud Run.",
      "1) Connect GitHub/GitLab/Cloud Source với Cloud Build.\n2) Tạo trigger: branch main → cloudbuild.yaml.\n3) Grant SA Cloud Build: Artifact Registry writer + Run deploy (hoặc custom hẹp hơn).\n4) Push commit; xem build trên console.\n5) Confirm revision Cloud Run mới xuất hiện.",
      "Using your personal user creds in CI instead of a service account breaks auditability.",
      "gcloud builds triggers create github --name=api-main --branch-pattern='^main$' --build-config=cloudbuild.yaml\ngcloud builds submit --config=cloudbuild.yaml ."),

    S("sec-cloudrun", "cloudbuild.yaml stages", "Build → push → deploy",
      "A minimal pipeline: (1) build image tagged with $SHORT_SHA, (2) push to Artifact Registry, (3) gcloud run deploy with that tag, (4) optional test step before deploy. Keep prod deploys on tags or protected branches if the team needs a gate.",
      "1) steps: docker build -t …:$SHORT_SHA .\n2) docker push …:$SHORT_SHA\n3) gcloud run deploy --image …:$SHORT_SHA\n4) Optional: wait-for / smoke curl\n5) images: or explicit push — be consistent",
      "Pipeline tối thiểu: (1) build image tag $SHORT_SHA, (2) push Artifact Registry, (3) gcloud run deploy với tag đó, (4) có thể thêm test trước deploy. Prod nên gắn tag hoặc protected branch nếu team cần gate.",
      "1) steps: docker build -t …:$SHORT_SHA .\n2) docker push …:$SHORT_SHA\n3) gcloud run deploy --image …:$SHORT_SHA\n4) Optional: smoke curl\n5) images: hoặc push tường minh — nhất quán",
      "A yaml that only builds but never deploys is CI without CD — say which you have.",
      "# cloudbuild.yaml (sketch)\n# steps:\n# - name: gcr.io/cloud-builders/docker\n#   args: ['build','-t','REGION-docker.pkg.dev/$PROJECT_ID/apps/api:$SHORT_SHA','.']\n# - name: gcr.io/cloud-builders/docker\n#   args: ['push','REGION-docker.pkg.dev/$PROJECT_ID/apps/api:$SHORT_SHA']\n# - name: gcr.io/google.com/cloudsdktool/cloud-sdk\n#   entrypoint: gcloud\n#   args: ['run','deploy','ielts-api','--image','…:$SHORT_SHA','--region','asia-southeast1','--quiet']"),

    S("sec-cloudrun", "Revisions, rollback, traffic", "Undo a bad release fast",
      "Each deploy = new revision. If error rate spikes, route traffic back to the previous healthy revision (rollback) while you fix forward. Canary: send 10% traffic to the new revision first.",
      "1) List revisions; identify last known good.\n2) gcloud run services update-traffic … --to-revisions=GOOD=100\n3) Or redeploy the previous image digest.\n4) Confirm logs/error rate recovered.\n5) Fix code; deploy again; optionally canary then 100%.",
      "Mỗi deploy = revision mới. Nếu error rate tăng, chuyển traffic về revision healthy trước (rollback) trong khi fix forward. Canary: 10% traffic revision mới trước.",
      "1) List revision; chọn last known good.\n2) gcloud run services update-traffic … --to-revisions=GOOD=100\n3) Hoặc deploy lại image digest cũ.\n4) Confirm log/error rate hồi.\n5) Fix code; deploy lại; có thể canary rồi 100%.",
      "Deleting the bad revision before investigating destroys forensic evidence — roll traffic first.",
      "gcloud run revisions list --service=ielts-api --region=asia-southeast1\ngcloud run services update-traffic ielts-api --region=asia-southeast1 --to-revisions=ielts-api-00042-abc=100"),

    S("sec-cloudrun", "Logs & debug Cloud Run", "Evidence over guesswork",
      "Use Cloud Logging for stdout/stderr from the container; filter by service/revision. Check request latency, cold starts, memory limits (OOM), and upstream Cloud SQL errors. Compare 'works locally' vs missing env on the revision.",
      "1) Open Logs for the Cloud Run service.\n2) Filter severity>=ERROR around the incident window.\n3) Note revision name on failing requests.\n4) Diff env/secrets vs last good revision.\n5) Reproduce with curl + correlation from logs.",
      "Dùng Cloud Logging cho stdout/stderr container; filter theo service/revision. Xem latency, cold start, memory (OOM), lỗi Cloud SQL upstream. So 'chạy local được' với thiếu env trên revision.",
      "1) Mở Logs của service Cloud Run.\n2) Filter severity>=ERROR quanh incident window.\n3) Ghi tên revision trên request lỗi.\n4) Diff env/secret với revision good.\n5) Reproduce bằng curl + correlation từ log.",
      "Restarting hope-fix without reading logs is not a strategy.",
      "gcloud logs read \"resource.type=cloud_run_revision AND resource.labels.service_name=ielts-api\" --limit=50"),

    S("sec-cloudrun", "Multi-env Cloud Run pattern", "dev / staging / prod services",
      "Prefer separate Cloud Run services or projects per env (ielts-api-staging vs ielts-api), each with its own SQL instance or database, secrets, and trigger. Promotion = deploy the same image tag to prod after staging smoke — or rebuild with prod substitutions if config is build-time.",
      "1) Name services clearly per env.\n2) Separate secrets and Cloud SQL.\n3) Staging trigger on main; prod trigger on tag/manual.\n4) Smoke staging URL before promoting.\n5) Document who can deploy prod.",
      "Nên tách service Cloud Run hoặc project theo env (ielts-api-staging vs ielts-api), mỗi bên SQL/secret/trigger riêng. Promote = deploy cùng image tag lên prod sau smoke staging — hoặc rebuild với substitution prod nếu config lúc build.",
      "1) Đặt tên service rõ theo env.\n2) Tách secret và Cloud SQL.\n3) Trigger staging trên main; prod trên tag/manual.\n4) Smoke URL staging trước khi promote.\n5) Document ai được deploy prod.",
      "One Cloud Run service shared by all envs with only an ENV var flipped is fragile for blast radius."),

    # ── sec-linux-vm ──────────────────────────────────────────────────────────
    S("sec-linux-vm", "Goal: Linux VM web server", "Classic hosting path",
      "Goal: stand up an Ubuntu/Debian VM on GCP, harden SSH, install a web server (Nginx/Apache; CV also includes LiteSpeed awareness), deploy a PHP/web app document root, open firewall correctly, add TLS, and troubleshoot with logs/disk. This matches Akktis day-to-day SSH ops for client sites.",
      "1) Create VM + SSH access.\n2) Update packages; install web server.\n3) Deploy app files + vhost.\n4) Firewall + TLS.\n5) Monitor logs/disk; harden basics.",
      "Mục tiêu: dựng VM Ubuntu/Debian trên GCP, harden SSH, install web server (Nginx/Apache; CV có LiteSpeed), deploy document root PHP/web, mở firewall đúng, thêm TLS, troubleshoot bằng log/disk. Khớp SSH ops hằng ngày ở Akktis cho site client.",
      "1) Tạo VM + SSH.\n2) Update package; install web server.\n3) Deploy file app + vhost.\n4) Firewall + TLS.\n5) Monitor log/disk; harden cơ bản.",
      "Don't claim you only use Cloud Run if the CV also lists Linux VM + LiteSpeed/Apache — own both paths."),

    S("sec-linux-vm", "Create & access a GCP VM", "Compute Engine first boot",
      "Create an e2-small (or appropriate) VM with Ubuntu LTS, pick region/zone, attach a public IP if it must serve the internet, and ensure your SSH key is registered (OS Login or project/instance metadata).",
      "1) gcloud compute instances create … --image-family=ubuntu-2204-lts …\n2) Note external IP.\n3) gcloud compute ssh USER@INSTANCE --zone=…\n4) Confirm uname -a and disk free.\n5) Set hostname / timezone if team standard requires.",
      "Tạo VM e2-small (hoặc phù hợp) Ubuntu LTS, chọn region/zone, gắn public IP nếu serve internet, đảm bảo SSH key đã đăng ký (OS Login hoặc metadata).",
      "1) gcloud compute instances create … --image-family=ubuntu-2204-lts …\n2) Ghi external IP.\n3) gcloud compute ssh USER@INSTANCE --zone=…\n4) Confirm uname -a và disk free.\n5) Set hostname/timezone nếu team yêu cầu.",
      "Leaving SSH open with password auth on a public IP is an avoidable incident.",
      "gcloud compute instances create web-1 --zone=asia-southeast1-b --machine-type=e2-small --image-family=ubuntu-2204-lts --image-project=ubuntu-os-cloud --tags=http-server,https-server\ngcloud compute ssh ubuntu@web-1 --zone=asia-southeast1-b"),

    S("sec-linux-vm", "SSH keys & first login hygiene", "Key-only access",
      "Prefer SSH public-key auth; disable password authentication after confirming key login works. Use a non-root sudo user. Keep private keys off chat/docs; use gcloud compute ssh or ssh-agent.",
      "1) Add your pubkey (ssh-ed25519…) via console/OS Login.\n2) Login; verify sudo -l.\n3) Edit sshd_config: PasswordAuthentication no; PermitRootLogin no (or prohibit-password).\n4) systemctl reload sshd carefully (keep a session open).\n5) Test a second SSH session before closing the first.",
      "Ưu tiên SSH pubkey auth; tắt password authentication sau khi confirm key login chạy. Dùng sudo user không phải root. Không gửi private key qua chat/docs; dùng gcloud compute ssh hoặc ssh-agent.",
      "1) Thêm pubkey (ssh-ed25519…) qua console/OS Login.\n2) Login; verify sudo -l.\n3) Sửa sshd_config: PasswordAuthentication no; PermitRootLogin no.\n4) systemctl reload sshd cẩn thận (giữ session cũ).\n5) Test SSH session thứ hai trước khi đóng session đầu.",
      "Reloading sshd after locking yourself out is a classic oops — always keep a backup session.",
      "ssh-keygen -t ed25519 -C 'you@work'\nsudo sed -n '1,120p' /etc/ssh/sshd_config\nsudo systemctl reload ssh"),

    S("sec-linux-vm", "apt update & install web server", "Nginx / Apache / LiteSpeed awareness",
      "Baseline: apt update && apt upgrade thoughtfully, then install Nginx or Apache. On Akktis work I also operate LiteSpeed for PHP/CMS apps — same ideas: document root, vhost, rewrite, PHP handler. Pick one primary for a greenfield VM; know how to read the other's config when inheriting a server.",
      "1) sudo apt update && sudo apt upgrade -y (maintenance window awareness).\n2) Install nginx or apache2 (+ php-fpm if PHP).\n3) systemctl enable --now nginx|apache2.\n4) curl localhost to verify default page.\n5) Note: LiteSpeed often has its own admin and config paths — don't invent panel passwords in interview; describe vhost + PHP + TLS concepts.",
      "Baseline: apt update && apt upgrade có chủ đích, rồi install Nginx hoặc Apache. Ở Akktis tôi cũng operate LiteSpeed cho app PHP/CMS — cùng ý: document root, vhost, rewrite, PHP handler. Greenfield chọn một; biết đọc config cái kia khi inherit server.",
      "1) sudo apt update && sudo apt upgrade -y (ý thức maintenance window).\n2) Install nginx hoặc apache2 (+ php-fpm nếu PHP).\n3) systemctl enable --now nginx|apache2.\n4) curl localhost confirm trang mặc định.\n5) LiteSpeed thường có admin/config path riêng — không bịa panel password; mô tả khái niệm vhost + PHP + TLS.",
      "Saying you 'optimized LiteSpeed' without naming what you changed (cache, PHP workers, vhost) is vague — give one concrete example.",
      "sudo apt update && sudo apt install -y nginx\n# or\nsudo apt install -y apache2 php-fpm\nsudo systemctl status nginx"),

    S("sec-linux-vm", "Firewall: GCP tags + UFW", "Only needed ports",
      "Two layers often: VPC firewall allowing 80/443 to the instance tag, and host UFW allowing OpenSSH + Nginx Full. Don't open MySQL to the world. Prefer IAP/tunnel for admin if the team uses it.",
      "1) Ensure instance has http-server/https-server tags (or custom rules).\n2) sudo ufw allow OpenSSH; sudo ufw allow 'Nginx Full' (or 80/443).\n3) sudo ufw enable.\n4) Verify from outside: curl http://EXTERNAL_IP.\n5) Confirm 22 only from trusted ranges if policy requires.",
      "Thường hai layer: VPC firewall cho 80/443 tới instance tag, và UFW trên host cho OpenSSH + Nginx Full. Không mở MySQL ra internet. Ưu tiên IAP/tunnel cho admin nếu team dùng.",
      "1) Instance có tag http-server/https-server (hoặc custom rule).\n2) sudo ufw allow OpenSSH; sudo ufw allow 'Nginx Full'.\n3) sudo ufw enable.\n4) Verify từ ngoài: curl http://EXTERNAL_IP.\n5) Port 22 chỉ từ trusted range nếu policy yêu cầu.",
      "ufw enable without allowing SSH first can lock you out.",
      "sudo ufw allow OpenSSH\nsudo ufw allow 'Nginx Full'\nsudo ufw enable\nsudo ufw status"),

    S("sec-linux-vm", "Deploy PHP/web app folder", "Document root & permissions",
      "Copy app to /var/www/app (or similar), set ownership to www-data (or the LiteSpeed/Apache user), keep secrets in env files outside the web root when possible, and run composer/migrations as documented for Laravel/WordPress/PrestaShop-style apps.",
      "1) sudo mkdir -p /var/www/app && deploy via git pull or rsync.\n2) chown -R www-data:www-data (or correct user).\n3) Place .env outside public/ if framework allows.\n4) Install PHP deps; set storage/cache writable.\n5) Point vhost document root at public/ (Laravel) or correct web root.",
      "Copy app vào /var/www/app (hoặc tương tự), chown www-data (hoặc user LiteSpeed/Apache), giữ secret ở file env ngoài web root khi được, chạy composer/migration theo docs cho app kiểu Laravel/WordPress/PrestaShop.",
      "1) sudo mkdir -p /var/www/app && deploy git pull hoặc rsync.\n2) chown -R www-data:www-data (hoặc user đúng).\n3) Đặt .env ngoài public/ nếu framework cho phép.\n4) Install PHP deps; cho phép ghi storage/cache.\n5) Trỏ vhost document root vào public/ (Laravel) hoặc web root đúng.",
      "chmod 777 -R 'to make uploads work' is a trap — fix ownership/group instead.",
      "sudo rsync -a ./ /var/www/app/\nsudo chown -R www-data:www-data /var/www/app\ncd /var/www/app && sudo -u www-data composer install --no-dev"),

    S("sec-linux-vm", "Vhost / systemd awareness", "Serve the right site",
      "Configure a server block (Nginx) or VirtualHost (Apache) with server_name, root, PHP-FPM socket, and access/error logs. Enable the site and reload. For long-running workers (queues), use systemd units — don't leave nohup forever without docs.",
      "1) Write /etc/nginx/sites-available/app.conf (or Apache sites-available).\n2) symlink into sites-enabled.\n3) nginx -t && systemctl reload nginx.\n4) Confirm Host header / DNS A record points to the VM.\n5) Optional: systemd unit for queue workers with Restart=on-failure.",
      "Config server block (Nginx) hoặc VirtualHost (Apache): server_name, root, PHP-FPM socket, access/error log. Enable site và reload. Worker dài (queue) dùng systemd — không để nohup mãi không docs.",
      "1) Viết /etc/nginx/sites-available/app.conf (hoặc Apache).\n2) symlink vào sites-enabled.\n3) nginx -t && systemctl reload nginx.\n4) Confirm DNS A / Host trỏ đúng VM.\n5) Optional: unit systemd cho queue với Restart=on-failure.",
      "Editing sites-enabled in place without nginx -t risks taking down all vhosts on reload.",
      "sudo ln -s /etc/nginx/sites-available/app.conf /etc/nginx/sites-enabled/\nsudo nginx -t && sudo systemctl reload nginx"),

    S("sec-linux-vm", "TLS with Let's Encrypt", "HTTPS concept",
      "Use Certbot (or equivalent) to obtain a Let's Encrypt certificate for the domain, auto-configure Nginx/Apache, and rely on renew timers. DNS must already point to the VM. Redirect HTTP→HTTPS.",
      "1) Point DNS A/AAAA to the VM IP; wait for propagation.\n2) sudo apt install certbot python3-certbot-nginx (or apache plugin).\n3) sudo certbot --nginx -d example.com.\n4) Confirm https:// loads with valid cert.\n5) Check renew: systemctl list-timers | grep certbot / certbot renew --dry-run.",
      "Dùng Certbot (hoặc tương đương) lấy Let's Encrypt certificate, config Nginx/Apache, dựa vào renew timer. DNS phải trỏ sẵn về VM. Redirect HTTP→HTTPS.",
      "1) Trỏ DNS A/AAAA về IP VM; chờ propagate.\n2) sudo apt install certbot python3-certbot-nginx.\n3) sudo certbot --nginx -d example.com.\n4) Confirm https:// load đúng cert.\n5) Check renew: timer certbot / certbot renew --dry-run.",
      "Self-signed certs are fine for lab; production public sites expect public CA trust.",
      "sudo certbot --nginx -d example.com\nsudo certbot renew --dry-run"),

    S("sec-linux-vm", "Logs & disk troubleshooting", "When the site dies quietly",
      "Symptoms: 5xx, blank page, can't write uploads, SSH still works. Check disk (df -h), inodes (df -i), journalctl/nginx error.log, PHP-FPM log, and recent deploys. Full disk is a classic production fire on CMS sites (logs, backups, uploads).",
      "1) df -h; df -i.\n2) du -sh /* | sort -h to find fat directories.\n3) Truncate/rotate bloated logs safely; move old backups off-box.\n4) Read /var/log/nginx/error.log or Apache/LiteSpeed error log.\n5) After cleanup, fix root cause (logrotate, retention).",
      "Symptom: 5xx, trang trắng, không ghi upload, SSH vẫn vào được. Check disk (df -h), inode (df -i), journalctl/nginx error.log, PHP-FPM log, deploy gần đây. Full disk là classic fire trên site CMS (log, backup, upload).",
      "1) df -h; df -i.\n2) du -sh /* | sort -h tìm directory phình.\n3) Truncate/rotate log an toàn; chuyển backup cũ khỏi máy.\n4) Đọc error log Nginx/Apache/LiteSpeed.\n5) Sau cleanup, fix root cause (logrotate, retention).",
      "Deleting files under /var/lib/mysql to free space is catastrophic — know what you're deleting.",
      "df -h\nsudo du -xh /var/log | sort -h | tail\nsudo journalctl -u nginx -n 100 --no-pager"),

    S("sec-linux-vm", "Harden basics checklist", "Practical, not theater",
      "Baseline hardening I actually practice and document: SSH key-only, UFW limited ports, unattended security updates where appropriate, separate sudo users, least privilege on app files, secrets not in web root, and clear runbooks so the next person isn't guessing.",
      "1) SSH keys only; no password auth.\n2) UFW/VPC least ports.\n3) Keep packages patched on a schedule.\n4) App file perms + secrets placement.\n5) Write short docs: how to deploy, where logs live, how to renew TLS.",
      "Harden baseline tôi thực hành và document: SSH chỉ key, UFW limit port, security update khi phù hợp, tách sudo user, least privilege cho file app, secret ngoài web root, runbook rõ để người sau không đoán.",
      "1) SSH chỉ key; tắt password auth.\n2) UFW/VPC mở tối thiểu port.\n3) Patch package theo schedule.\n4) App file perm + vị trí secret.\n5) Docs ngắn: cách deploy, log ở đâu, renew TLS thế nào.",
      "I'm not claiming a full enterprise security audit — I claim practical hardening + documentation.",
      "sudo apt install -y unattended-upgrades\nsudo ufw status verbose\n# document: /root/runbooks/web-deploy.md (team path)"),
]
