# FACTS (creation gate):
# 1) Caller: _build/gen_vnpt.py line ~14: from cards_part1b import CARDS as C1B
# 2) Glob: no cards_part1b.py exists yet
# 3) Data shape (synthetic): {sec, kind, title, sub, c_en, m_en, c_vi, m_vi, crib, note} — no dates
# 4) User: Create complete offline HTML at interview-cheatsheet/vnpt-devops.html
#
# Card data: sec-security through sec-docker. Imported by gen_vnpt.py only.

def C(sec, title, sub, c_en, m_en, c_vi, m_vi, crib="", note=""):
    return {
        "sec": sec, "kind": "concept", "title": title, "sub": sub,
        "c_en": c_en, "m_en": m_en, "c_vi": c_vi, "m_vi": m_vi,
        "crib": crib, "note": note,
    }


CARDS = [
    C("sec-security", "AuthN vs AuthZ", "Who you are vs what you can do",
      "Authentication verifies identity (password, SSO, mTLS, tokens). Authorization decides permissions (RBAC, policies). Never conflate them in design discussions.",
      "In K8s: AuthN via certs/OIDC/tokens; AuthZ via RBAC Roles/ClusterRoles.",
      "Authentication xác minh danh tính. Authorization quyết định quyền. Đừng gộp hai khái niệm khi thảo luận thiết kế.",
      "Trong K8s: AuthN qua cert/OIDC/token; AuthZ qua RBAC.",
      "Shared admin accounts break auditability."),
    C("sec-security", "Secrets management", "Never in Git",
      "Secrets: passwords, tokens, keys, certs. Store in vault/secret managers or sealed mechanisms; inject at runtime; rotate; least scope.",
      "CI secrets belong in credential stores (Jenkins credentials, GitLab CI variables protected/masked), not YAML in repo.",
      "Secret: mật khẩu, token, key, cert. Lưu vault/secret manager; inject runtime; xoay vòng; phạm vi tối thiểu.",
      "Secret CI nằm ở credential store (Jenkins credentials, GitLab variables protected/masked), không nằm YAML trong repo.",
      "base64 in K8s Secret is encoding only, not encryption at rest by itself.",
      "echo -n 'secret' | base64  # encoding only, not encryption"),
    C("sec-security", "Least privilege and hardening", "Reduce blast radius",
      "Give users/services only required permissions. Harden hosts: disable unused services, patch, SSH key auth, firewall defaults deny, non-root containers when possible.",
      "ATTT collaboration: accept findings, agree severity/SLA, remediate or document risk acceptance.",
      "Chỉ cấp quyền cần thiết. Hardening: tắt service thừa, vá lỗi, SSH key, firewall default deny, container non-root khi được.",
      "Phối hợp ATTT: nhận finding, thống nhất mức độ/SLA, khắc phục hoặc ghi nhận chấp nhận rủi ro.",
      "Running containers as root because Dockerfile was easier is a common bad habit."),
    C("sec-security", "TLS and secure transport", "In transit protection",
      "Use TLS for external and sensitive internal traffic. Prefer modern ciphers; redirect HTTP to HTTPS at the edge; pin internal mTLS where policies require.",
      "Know difference between encrypt-in-transit and encrypt-at-rest.",
      "Dùng TLS cho traffic ngoài và nội bộ nhạy cảm. Cipher hiện đại; redirect HTTP sang HTTPS; mTLS nội bộ khi policy yêu cầu.",
      "Phân biệt mã hóa khi truyền và khi lưu trữ.",
      "Terminating TLS at LB then sending plaintext across untrusted segments without compensating controls is risky."),
    C("sec-security", "Logging for security", "Audit trails",
      "Security-relevant logs: auth success/fail, privilege changes, admin actions, deploy events, firewall denies. Protect log integrity and access.",
      "Ship to ELK/SIEM with retention per policy. DevOps helps ATTT by ensuring logs exist and are queryable.",
      "Log liên quan ATTT: đăng nhập thành công/thất bại, đổi quyền, hành động admin, sự kiện deploy, firewall deny. Bảo vệ toàn vẹn và quyền truy cập log.",
      "Đẩy vào ELK/SIEM với retention theo policy. DevOps giúp ATTT bằng cách đảm bảo log tồn tại và truy vấn được.",
      "Logging secrets/PII in plaintext application logs is itself a security incident."),
    C("sec-security", "Working with ATTT (security team)", "Process, not combat",
      "Treat ATTT as partners: triage findings by exploitability/impact, propose fixes (patch, WAF rule, network segment, secret rotation), give clear ETAs, verify closure.",
      "Bring evidence: CVE id, affected hosts/images, compensating controls, test plan after fix.",
      "Coi ATTT là đối tác: phân loại theo khả năng khai thác/ảnh hưởng, đề xuất fix, ETA rõ, xác nhận đóng finding.",
      "Mang bằng chứng: CVE, host/image ảnh hưởng, biện pháp bù, kế hoạch test sau fix.",
      "Dismissing scanner findings without checking reachability/version looks careless."),
    C("sec-security", "Supply chain and image hygiene", "Trust what you run",
      "Prefer minimal base images, pin digests/tags, scan images (Trivy/Grype class tools), sign if platform supports, avoid latest in prod.",
      "CI should fail or warn on critical CVEs per policy.",
      "Ưu tiên base image tối giản, pin digest/tag, quét image, ký nếu hỗ trợ, tránh latest trên prod.",
      "CI nên fail/warn với CVE critical theo policy.",
      "Rebuilding from latest weekly without reviewing changelogs/CVEs is risky.",
      "trivy image myrepo/app:1.2.3"),

    C("sec-git", "Git basics that tests love", "commit, branch, merge, rebase awareness",
      "Working tree to stage to commit to push. Branches isolate work. merge combines histories; rebase replays commits (rewrite — careful on shared branches).",
      "Know conflict resolution, .gitignore, and that force-push to main is dangerous.",
      "Working tree sang stage sang commit sang push. Branch tách việc. merge gộp lịch sử; rebase phát lại commit (cẩn thận trên nhánh chia sẻ).",
      "Biết giải conflict, .gitignore, và force-push main rất nguy hiểm.",
      "Committing node_modules/binaries/secrets is a common fail.",
      "git status; git diff\ngit switch -c feature/x\ngit commit -m 'msg'\ngit push -u origin HEAD\ngit log --oneline -n 10"),
    C("sec-git", "Branching for teams", "GitFlow-ish vs trunk-based",
      "Common patterns: trunk-based with short-lived PRs, or GitFlow-like (main/develop/feature/release). Pick what the team already uses.",
      "Protect main with required checks + reviews. Prefer small PRs.",
      "Pattern phổ biến: trunk-based với PR ngắn sống, hoặc GitFlow-like. Theo convention team.",
      "Bảo vệ main bằng check bắt buộc + review. Ưu tiên PR nhỏ.",
      "Long-lived feature branches that diverge for weeks create merge pain."),
    C("sec-git", "GitLab and Bitbucket in delivery", "Hosted Git + MR/PR",
      "GitLab/Bitbucket host repos, MRs/PRs, permissions, and often CI. Merge requests carry discussion, pipelines, and approvals.",
      "Know protected branches, CODEOWNERS-like rules, and artifact registries if used.",
      "GitLab/Bitbucket chứa repo, MR/PR, phân quyền, thường kèm CI. MR mang thảo luận, pipeline, approval.",
      "Biết protected branch, rule sở hữu code, registry artifact nếu có.",
      "Approving MRs without reading pipeline failure reasons is careless."),
    C("sec-git", "Jira in the delivery loop", "Traceability",
      "Jira tracks work items; good teams link commits/MRs/deploys to tickets for audit and release notes.",
      "DevOps helps by automating status transitions and including ticket IDs in commit messages/changelog.",
      "Jira theo dõi công việc; team tốt liên kết commit/MR/deploy với ticket để audit và release note.",
      "DevOps hỗ trợ tự động chuyển trạng thái và gắn ID ticket vào commit/changelog.",
      "Treating Jira updates as bureaucracy only ignores auditors and on-call who need the trail."),
    C("sec-git", "Code review and hooks", "Quality before merge",
      "Human review catches design issues; CI catches regressions. Pre-commit/hooks can format/lint locally but should not be the only gate.",
      "As DevOps, keep required checks green and meaningful.",
      "Review người bắt lỗi thiết kế; CI bắt regression. Hook local hữu ích nhưng không phải gate duy nhất.",
      "Với DevOps: giữ required check xanh và có ý nghĩa.",
      "Optional checks that everyone ignores train bad habits."),
    C("sec-git", "Tagging and releases", "Immutable references",
      "Tags mark releases (v1.2.3). Prefer annotated tags. Deploy by tag/digest, not floating branch, for prod.",
      "Changelog + tag + artifact version should align.",
      "Tag đánh dấu release. Ưu tiên annotated tag. Deploy prod theo tag/digest, không theo branch trôi.",
      "Changelog + tag + version artifact phải khớp.",
      "Retagging the same version to a different commit breaks provenance.",
      "git tag -a v1.2.3 -m 'release'\ngit push origin v1.2.3"),

    C("sec-cicd", "Jenkins concepts", "Jobs, agents, pipelines",
      "Jenkins orchestrates builds via Freestyle or (preferred) Pipeline-as-code (Jenkinsfile). Agents/executors run steps. Plugins extend SCM, credentials, Docker, etc.",
      "Know master/controller vs agent, credentials binding, and multibranch pipelines.",
      "Jenkins điều phối build qua Freestyle hoặc Pipeline-as-code (Jenkinsfile). Agent chạy step. Plugin mở rộng SCM, credential, Docker...",
      "Biết controller vs agent, credentials binding, multibranch pipeline.",
      "Storing secrets in plain Jenkinsfile is a critical fail.",
      "jenkins stages example: checkout, build, test, package, deploy"),
    C("sec-cicd", "GitLab CI concepts", "Stages, runners, .gitlab-ci.yml",
      "GitLab CI uses .gitlab-ci.yml with stages/jobs, runners execute jobs, artifacts/cache speed builds, environments track deploys.",
      "Know rules/only-except, protected variables, and DAGs via needs.",
      "GitLab CI dùng .gitlab-ci.yml với stage/job; runner thực thi; artifact/cache; environment theo dõi deploy.",
      "Biết rules, biến protected, needs để tạo DAG.",
      "Shared runners with privileged Docker without understanding security impact is dangerous.",
      "stages: [build, test, package, deploy]"),
    C("sec-cicd", "Typical pipeline stages", "A reusable mental model",
      "checkout → dependency install → build → unit/integration tests → security scan → package (jar/image) → push registry → deploy (dev/staging/prod) → smoke test → notify.",
      "Fail fast on unit tests; heavier scans can be parallel; prod deploy often needs approval.",
      "checkout → cài dependency → build → test → scan → package → push registry → deploy → smoke → notify.",
      "Fail nhanh ở unit test; scan nặng có thể song song; deploy prod thường cần approval.",
      "Deploying without smoke checks after release is gambling."),
    C("sec-cicd", "Artifacts and versioning", "What you ship",
      "Artifacts are build outputs (binaries, images, SBOM). Version them immutably; promote the same artifact across envs when possible.",
      "Do not rebuild differently for prod if you can promote.",
      "Artifact là đầu ra build (binary, image, SBOM). Version bất biến; nên promote cùng artifact qua các môi trường.",
      "Tránh build khác cho prod nếu promote được.",
      "latest tag as the only prod reference is fragile."),
    C("sec-cicd", "Secrets in CI", "Credential hygiene",
      "Use platform credential stores; mask logs; restrict who can read variables; rotate regularly; scope tokens to least privilege (registry push-only, deploy-only).",
      "Avoid printing env in debug on shared runners.",
      "Dùng credential store của nền tảng; che log; hạn chế ai đọc biến; rotate; token tối thiểu quyền.",
      "Tránh in env debug trên shared runner.",
      "Enabling debug mode that echoes secrets into build logs is a classic leak."),
    C("sec-cicd", "Quality gates", "When to block the merge",
      "Gates: tests green, coverage threshold (if agreed), critical CVE policy, lint for risky configs, signed commits/images if required.",
      "Make failures actionable with clear logs and ownership.",
      "Gate: test xanh, coverage (nếu thống nhất), CVE critical, lint config rủi ro, ký commit/image nếu yêu cầu.",
      "Fail phải actionable: log rõ, có owner.",
      "Flaky gates train people to retry blindly."),
    C("sec-cicd", "Deploy strategies awareness", "Rolling, blue/green, canary",
      "Rolling: gradually replace instances. Blue/green: switch traffic between two stacks. Canary: small percent traffic then expand. Choose by risk and tooling.",
      "Always have rollback: previous image/tag, DB migration compatibility, feature flags.",
      "Rolling: thay dần instance. Blue/green: chuyển traffic giữa hai stack. Canary: phần trăm nhỏ rồi mở rộng.",
      "Luôn có rollback: image/tag trước, tương thích migration DB, feature flag.",
      "Canary without metrics to decide promote/rollback is theater."),
    C("sec-cicd", "Jenkins vs GitLab CI (practical)", "When asked to compare",
      "Jenkins: extremely flexible, plugin ecosystem, more ops overhead. GitLab CI: integrated with GitLab MR UX, YAML-first, runners to manage. Both can build/test/deploy Docker/K8s.",
      "Answer with tradeoffs, not X is always better.",
      "Jenkins: linh hoạt, plugin nhiều, tốn ops hơn. GitLab CI: gắn MR UX, YAML-first, cần quản lý runner. Cả hai đều build/test/deploy Docker/K8s được.",
      "Trả lời theo tradeoff, không nói X luôn tốt hơn.",
      "Tool wars without mentioning team skills and existing estate are shallow."),

    C("sec-automation", "Ansible mental model", "Inventory, playbooks, modules",
      "Ansible pushes config over SSH (agentless). Inventory lists hosts/groups; playbooks list plays/tasks; modules do idempotent work (apt, copy, service).",
      "Idempotency: run twice → same end state. Use check mode and diff when safe.",
      "Ansible đẩy cấu hình qua SSH (không agent). Inventory liệt kê host; playbook gồm task; module làm việc idempotent.",
      "Idempotency: chạy hai lần → cùng trạng thái. Dùng --check/--diff khi an toàn.",
      "shell/command tasks that always change defeat idempotency — prefer modules.",
      "ansible all -m ping -i inventory\nansible-playbook -i inventory site.yml --check --diff"),
    C("sec-automation", "Ansible variables and roles", "Structure for reuse",
      "Vars come from inventory, group_vars/host_vars, playbook, extra-vars (precedence matters). Roles package tasks/handlers/templates.",
      "Handlers run once if notified (e.g., restart nginx after config change).",
      "Biến từ inventory, group_vars/host_vars, playbook, extra-vars (có thứ tự ưu tiên). Role đóng gói task/handler/template.",
      "Handler chạy một lần nếu được notify (ví dụ restart nginx).",
      "Putting secrets in group_vars committed to Git — use Ansible Vault or external secret injection.",
      "ansible-vault encrypt group_vars/prod/vault.yml"),
    C("sec-automation", "Bash scripting patterns for ops", "Safe, boring scripts",
      "Use set -euo pipefail where appropriate; quote variables; prefer absolute paths; log to file; exit codes; avoid destructive defaults.",
      "Validate inputs; dry-run flags for risky ops; do not parse ls.",
      "Dùng set -euo pipefail khi phù hợp; quote biến; đường dẫn tuyệt đối; ghi log; mã thoát; tránh mặc định phá hủy.",
      "Validate input; cờ dry-run cho thao tác rủi ro; đừng parse ls.",
      "Unquoted $files expanding spaces can wipe wrong paths.",
      "#!/usr/bin/env bash\nset -euo pipefail\nlog(){ echo \"[$(date -Is)] $*\"; }"),
    C("sec-automation", "Python for DevOps glue", "APIs, parsing, automation",
      "Python shines for API clients (cloud/K8s/GitLab), parsing JSON/YAML, generating configs, small CLIs. Use venv; pin deps; handle errors/timeouts.",
      "Not every task needs Python — Bash for simple glue, Ansible for config drift, Python for logic/APIs.",
      "Python mạnh với API client, parse JSON/YAML, sinh config, CLI nhỏ. Dùng venv; pin dependency; xử lý lỗi/timeout.",
      "Không phải việc nào cũng cần Python — Bash cho glue đơn giản, Ansible cho drift, Python cho logic/API.",
      "One-off scripts without requirements.txt become unmaintainable.",
      "python3 -m venv .venv && . .venv/bin/activate\npip install requests pyyaml"),
    C("sec-automation", "Idempotency and drift", "Why automation fails in prod",
      "Drift = reality differs from declared state (manual hotfix). Detect with config management check mode, GitOps diffs, or periodic compliance scans.",
      "Policy: either fix forward via code or accept temporary hotfix with ticket + deadline.",
      "Drift = thực tế khác trạng thái khai báo (hotfix tay). Phát hiện bằng check mode, diff GitOps, hoặc quét định kỳ.",
      "Policy: sửa bằng code hoặc chấp nhận hotfix tạm kèm ticket + deadline.",
      "Silent manual changes in prod with no ticket create future outages."),
    C("sec-automation", "Inventory realities", "Dynamic vs static",
      "Static inventory files work for small estates; dynamic inventory pulls from cloud/CMDB. Group by role/env (web, db, prod, staging).",
      "Keep naming consistent with monitoring and CMDB.",
      "Inventory tĩnh cho hệ thống nhỏ; dynamic lấy từ cloud/CMDB. Group theo role/env.",
      "Đặt tên nhất quán với monitoring và CMDB.",
      "One flat list of IPs with no groups makes playbooks unreadable."),
    C("sec-automation", "When not to automate yet", "Judgment",
      "Do not automate a process you do not understand. First make it reliable manually, document, then automate the stable path.",
      "Automate toil (repetitive, error-prone); keep humans for novel incidents.",
      "Đừng tự động hóa quy trình chưa hiểu. Làm tay ổn định, ghi docs, rồi mới automate.",
      "Tự động hóa toil; giữ người cho sự cố mới lạ.",
      "Automating a broken process gives you faster failures."),

    C("sec-docker", "Images, containers, layers", "Core model",
      "Image = immutable layered filesystem + metadata. Container = running instance with writable layer. Layers cache builds; order Dockerfile for cache hits.",
      "Union filesystem means deleting a file in a later layer does not shrink earlier layers.",
      "Image = filesystem phân lớp bất biến + metadata. Container = instance đang chạy với lớp ghi. Layer cache build; sắp xếp Dockerfile để tận dụng cache.",
      "Union FS: xóa file ở layer sau không làm nhỏ layer trước.",
      "Expecting image size to shrink after RUN rm of files added in previous layers without squash/multi-stage is a common trap.",
      "docker images; docker ps -a\ndocker history myimg:1"),
    C("sec-docker", "Dockerfile best practices", "Small, safe, reproducible",
      "Use specific base tags/digests; multi-stage builds; .dockerignore; non-root USER; minimal packages; HEALTHCHECK optional; one concern per image.",
      "Prefer COPY over ADD; pin versions; do not store secrets in ENV/layers.",
      "Base tag/digest cụ thể; multi-stage; .dockerignore; USER non-root; ít package; một trách nhiệm/image.",
      "Ưu tiên COPY hơn ADD; pin version; không để secret trong ENV/layer.",
      "apt-get without rm lists bloats layers; secrets in ARG can persist.",
      "FROM node:20-alpine AS build\nWORKDIR /app\nCOPY package*.json .\nRUN npm ci\nCOPY . .\nRUN npm run build\nFROM node:20-alpine\nUSER node\nCOPY --from=build /app/dist ./dist"),
    C("sec-docker", "Volumes and bind mounts", "Persistence",
      "Container filesystem is ephemeral. Volumes persist data beyond container lifecycle; bind mounts map host paths (dev convenience, careful in prod).",
      "Know permissions/UID issues when mounting.",
      "FS container là tạm. Volume giữ dữ liệu vượt vòng đời container; bind mount map path host (tiện dev, cẩn thận prod).",
      "Chú ý quyền/UID khi mount.",
      "Putting DB data only in container writable layer means data lost on recreate.",
      "docker volume ls\ndocker run -v pgdata:/var/lib/postgresql/data postgres:16"),
    C("sec-docker", "Docker networks", "How containers talk",
      "Bridge networks connect containers by name on user-defined networks. Host/network modes have tradeoffs. Publish ports with -p carefully.",
      "Prefer user-defined bridge over default for DNS between containers.",
      "Bridge network cho container nói chuyện theo tên. Host network có tradeoff. Publish port bằng -p cẩn thận.",
      "Ưu tiên user-defined bridge để DNS giữa container.",
      "Hardcoding container IPs fails when IPs change.",
      "docker network create appnet\ndocker run --network appnet --name api ..."),
    C("sec-docker", "Registry and tagging", "Distribute images",
      "Push/pull from Docker Hub or private registry (Harbor/ECR/GitLab Registry). Tag with semver + git sha; pin digests in prod manifests.",
      "Authenticate with least-privilege tokens.",
      "Push/pull từ Hub hoặc registry riêng. Tag semver + git sha; pin digest trên prod.",
      "Xác thực bằng token tối thiểu quyền.",
      "Mutable tags silently changing what prod runs break reproducibility.",
      "docker tag app:1.2.3 registry.example/app:1.2.3\ndocker push registry.example/app:1.2.3"),
    C("sec-docker", "Runtime pitfalls", "Debug containers",
      "Common issues: crash loops (check logs), bad CMD/ENTRYPOINT, missing env, permission denied, OOM kills, port not published, healthcheck failing.",
      "docker logs / exec / inspect are first tools; do not exec into prod casually without policy.",
      "Vấn đề thường: crash loop, CMD/ENTRYPOINT sai, thiếu env, permission, OOM, chưa publish port, healthcheck fail.",
      "docker logs/exec/inspect là công cụ đầu; exec prod phải theo policy.",
      "It works on my Docker Desktop with different arch/volume paths is a common false green.",
      "docker logs -f --tail=200 cname\ndocker inspect cname\ndocker exec -it cname sh"),
    C("sec-docker", "Resource limits", "CPU and memory",
      "Without limits, a container can starve the host. Use --memory/--cpus (or compose/K8s equivalents).",
      "Align app JVM/heap settings with container limits.",
      "Không limit thì container có thể ăn hết host. Dùng --memory/--cpus (hoặc tương đương compose/K8s).",
      "Chỉnh heap JVM khớp limit container.",
      "Container limit 512Mi while JVM heap set to 1g causes instant OOM.",
      "docker run --memory=512m --cpus=1.0 ..."),
    C("sec-docker", "Compose awareness", "Multi-container local/dev",
      "docker compose defines services, networks, volumes in YAML for local stacks. Good for dev parity; prod often moves to K8s.",
      "Keep compose secrets out of committed files.",
      "Compose định nghĩa service/network/volume bằng YAML cho stack local. Tốt cho dev; prod thường lên K8s.",
      "Không commit secret trong compose.",
      "Using compose in prod without understanding restart/HA limitations is risky.",
      "docker compose up -d\ndocker compose ps\ndocker compose logs -f"),
]
