# Card data: sec-jd through sec-network. Imported by gen_vnpt.py (from cards_part1a import CARDS).
# No other callers. Synthetic study content only.
# Shape: {sec, kind, title, sub, c_en, m_en, c_vi, m_vi, crib?, note?} — no date fields.

def C(sec, title, sub, c_en, m_en, c_vi, m_vi, crib="", note=""):
    return {
        "sec": sec, "kind": "concept", "title": title, "sub": sub,
        "c_en": c_en, "m_en": m_en, "c_vi": c_vi, "m_vi": m_vi,
        "crib": crib, "note": note,
    }


CARDS = [
    C("sec-jd", "VNPT DevOps JD at a glance", "What the role asks vs what the test checks",
      "Role: DevOps engineer supporting delivery — CI/CD with developers, monitoring/alerting, incident recovery, backup/restore, collaborate with ATTT (security), contribute to architecture.",
      "JD tool keywords: Jenkins, Jira, Git/GitLab/Bitbucket, Grafana, Prometheus, Ansible, Docker, Kubernetes (HA), Apache, Nginx, ELK; language awareness Java/Python/Bash; OS topics process/threads/concurrency/sockets/I/O/virtualization/memory/filesystems; AI/LLM applied to DevOps.",
      "Vai trò: kỹ sư DevOps hỗ trợ delivery — CI/CD với dev, giám sát/cảnh báo, xử lý sự cố, backup/restore, phối hợp ATTT, đóng góp kiến trúc.",
      "Từ khóa JD: Jenkins, Jira, Git/GitLab/Bitbucket, Grafana, Prometheus, Ansible, Docker, Kubernetes (HA), Apache, Nginx, ELK; Java/Python/Bash; OS: process/threads/concurrency/sockets/I/O/virtualization/memory/filesystems; AI/LLM trong DevOps.",
      "Listing tools is not understanding. Be ready to explain how CI stages, probes, or alerts actually work."),
    C("sec-jd", "Pre-test vs interview", "How to allocate study time",
      "Per VNPTips #2, the VNPT screening test is usually multiple choice (trắc nghiệm): foundational theory, situational reasoning, and job-applied questions. Drill definitions, commands, and pick-the-best-option logic (OS, network, Linux, Docker/K8s, CI concepts).",
      "Interview (after the test) checks spoken judgment: broken pipeline, restore, alert storm, ATTT collaboration — with honest hands-on stories. Study Part 'Exam tips + MCQ' before the screen; Part Fit/Scenarios before interview day.",
      "Theo VNPTips #2, vòng thi tuyển VNPT thường là trắc nghiệm: lý thuyết nền, tình huống, và ứng dụng vị trí. Ôn định nghĩa, lệnh, và tư duy chọn đáp án đúng nhất (OS, mạng, Linux, Docker/K8s, CI).",
      "Phỏng vấn (sau bài thi) kiểm tra phán đoán nói: pipeline hỏng, restore, bão alert, phối hợp ATTT — kèm câu chuyện hands-on. Ôn phần 'Exam tips + MCQ' trước vòng thi; Fit/Scenarios trước ngày PV.",
      "Don't invent VNPT-internal platforms. Speak general enterprise DevOps practice."),
    C("sec-jd", "Duty map: deploy & CI/CD", "JD verb to study topic",
      "Deploy CI/CD with developers maps to Jenkins/GitLab CI stages, artifacts, secrets, quality gates, Git branching, and Jira delivery loop.",
      "Be able to describe a pipeline: checkout, build, test, scan, package image, deploy, notify; where secrets live; how rollbacks work.",
      "Triển khai CI/CD cùng developer gắn với Jenkins/GitLab CI, artifact, secret, quality gate, Git branch, vòng Jira.",
      "Mô tả được pipeline: checkout, build, test, scan, package image, deploy, notify; secret nằm đâu; rollback thế nào.",
      "Saying we use Jenkins without stages/artifacts/approval gates is a weak answer."),
    C("sec-jd", "Duty map: monitor, recover, backup, ATTT", "Ops loop",
      "Monitoring/alerting maps to Prometheus metrics, Grafana dashboards, ELK logs, on-call hygiene. Incident recovery maps to runbooks, rollback, postmortem. Backup maps to RPO/RTO and restore tests. ATTT maps to least privilege, secrets, hardening, audit logs.",
      "Architecture contribution means knowing HA vs DR, layers, LB, multi-replica K8s patterns — not claiming you designed VNPT's whole platform.",
      "Giám sát/cảnh báo: Prometheus, Grafana, ELK, on-call. Phục hồi sự cố: runbook, rollback, postmortem. Backup: RPO/RTO và test restore. ATTT: least privilege, secret, hardening, log audit.",
      "Đóng góp kiến trúc = hiểu HA vs DR, lớp hệ thống, LB, pattern multi-replica K8s — không nhận thiết kế cả nền tảng VNPT.",
      "Monitoring without knowing what to alert on (SLO/symptoms vs every spike) fails interviews."),
    C("sec-jd", "Honesty posture for this prep", "Strong hands-on, precise claims",
      "Speak as someone who has run CI/CD, containers, K8s, and monitoring in real projects. Prefer 'I did X in Y context' over buzzwords.",
      "AI/LLM: practical assistants for scripts, log triage, docs, pipeline help — do not claim production LLM platforms unless true. No fabricated VNPT internals.",
      "Nói như người đã chạy CI/CD, container, K8s, monitoring trong dự án thật. Ưu tiên 'tôi làm X trong ngữ cảnh Y' hơn buzzword.",
      "AI/LLM: trợ lý thực tế cho script, đọc log, docs, pipeline — không nhận vận hành nền tảng LLM production nếu chưa làm. Không bịa hệ thống nội bộ VNPT.",
      "If asked about a tool you only studied: say research/lab level clearly, then how you'd ramp up."),

    C("sec-devops", "What is DevOps?", "Culture + practices + tooling",
      "DevOps is a way of working that shortens the path from commit to reliable production by combining culture, automation, measurement, and shared ownership between Dev and Ops.",
      "Tools enable DevOps; they don't replace feedback loops, blameless learning, and clear ownership of deploy/monitor/recover.",
      "DevOps là cách làm việc rút ngắn đường từ commit đến production ổn định bằng văn hóa, tự động hóa, đo lường và ownership chung giữa Dev và Ops.",
      "Tool hỗ trợ DevOps; không thay thế vòng phản hồi, học không đổ lỗi, và ownership rõ về deploy/monitor/recover.",
      "DevOps equals installing Jenkins is wrong. Jenkins is one CI tool inside a broader practice."),
    C("sec-devops", "SDLC and where DevOps sits", "Plan through learn loop",
      "Classic SDLC phases still exist; DevOps accelerates feedback across them with automation and observability.",
      "In interviews, map your work to the loop: requirements in Jira, Git, CI, deploy, metrics/logs, improve.",
      "Các pha SDLC vẫn còn; DevOps tăng tốc phản hồi xuyên suốt bằng automation và observability.",
      "Khi phỏng vấn, map công việc vào vòng: yêu cầu Jira, Git, CI, deploy, metrics/logs, cải thiện.",
      "Treating ops as after-release only is outdated — modern DevOps owns operate and learn too."),
    C("sec-devops", "CALMS model", "Culture, Automation, Lean, Measurement, Sharing",
      "CALMS is a checklist for DevOps maturity: Culture (blame-free collab), Automation (repeatable pipelines), Lean (small batches), Measurement (SLIs/alerts), Sharing (docs/runbooks).",
      "Use CALMS to explain why a shiny tool failed: often culture/measurement/sharing were missing.",
      "CALMS là checklist độ chín DevOps: Culture, Automation, Lean, Measurement, Sharing.",
      "Dùng CALMS giải thích vì sao tool đẹp vẫn fail: thường thiếu văn hóa/đo lường/chia sẻ.",
      "Memorizing the acronym without an example of measurement (latency, error rate, deploy frequency) is weak."),
    C("sec-devops", "CI vs CD vs GitOps", "Precise definitions",
      "CI (Continuous Integration): automatically build/test every change so main stays healthy. CD often means Continuous Delivery (always releasable) or Continuous Deployment (auto to prod). GitOps: desired state in Git; a controller reconciles clusters to that state.",
      "Say which meaning of CD you use. GitOps is a delivery pattern (usually for K8s), not a replacement for CI tests.",
      "CI: tự động build/test mỗi thay đổi để nhánh chính khỏe. CD: Continuous Delivery (luôn sẵn sàng release) hoặc Continuous Deployment (tự lên prod). GitOps: trạng thái mong muốn trong Git; controller đồng bộ cluster.",
      "Nói rõ bạn đang dùng nghĩa CD nào. GitOps là pattern delivery (thường K8s), không thay test CI.",
      "GitOps means no CI is false; you still build/test/sign artifacts."),
    C("sec-devops", "Infrastructure as Code (IaC)", "Declarative repeatability",
      "IaC means defining infra/config in versioned code (Terraform, Ansible, Helm, Kustomize) so environments are reproducible and reviewable.",
      "Benefits: audit trail, PR review, less snowflake servers. Risks: drift if people change prod by hand; secrets leaking into repos.",
      "IaC: mô tả infra/config bằng code có version (Terraform, Ansible, Helm, Kustomize) để môi trường lặp lại và review được.",
      "Lợi ích: audit, PR review, ít server snowflake. Rủi ro: drift nếu sửa prod tay; lộ secret trong repo.",
      "Checking secrets into Git just for the lab is never acceptable habit.",
      "ansible-playbook site.yml --check\nterraform plan"),
    C("sec-devops", "Shift-left and quality gates", "Fail fast",
      "Shift-left moves tests, security scans, and policy checks earlier so bugs are cheaper. Quality gates can block merge/deploy on failed tests or critical CVEs.",
      "Balance speed vs gates: critical security/tests block; warnings inform. Document exceptions with expiry.",
      "Shift-left: đẩy test, quét bảo mật, policy sớm hơn. Quality gate có thể chặn merge/deploy khi fail test hoặc CVE nghiêm trọng.",
      "Cân bằng tốc độ vs gate: lỗi bảo mật/test quan trọng thì chặn; warning thì thông báo. Exception phải có hạn.",
      "Forty flaky gates that everyone skips are worse than fewer solid gates."),
    C("sec-devops", "DevOps metrics that matter", "DORA-style awareness",
      "Useful metrics: deploy frequency, lead time for changes, change failure rate, MTTR. Pair with user-facing SLIs (latency, availability, error rate).",
      "Metrics drive improvement conversations, not blame. Know MTTR vs MTTD (detect).",
      "Chỉ số hữu ích: tần suất deploy, lead time, tỉ lệ thay đổi lỗi, MTTR. Kết hợp SLI hướng người dùng (latency, availability, error rate).",
      "Metrics để cải thiện, không để đổ lỗi. Biết MTTR vs MTTD (thời gian phát hiện).",
      "Optimizing deploy count while error rate explodes is the wrong game."),

    C("sec-linux", "Users, groups, permissions", "rwx and ownership",
      "Linux access uses user/group/other bits (r/w/x) plus ownership. Special bits: setuid/setgid/sticky. Prefer groups + least privilege over chmod 777.",
      "Read ls -l: type, perms, links, owner, group, size, mtime, name. Use id, groups, sudo -l to see your effective rights.",
      "Quyền Linux: user/group/other (r/w/x) và ownership. Bit đặc biệt: setuid/setgid/sticky. Ưu tiên group + least privilege, tránh chmod 777.",
      "Đọc ls -l: loại, quyền, link, owner, group, size, mtime, tên. Dùng id, groups, sudo -l để xem quyền thực tế.",
      "chmod 777 to make it work hides root cause and opens security holes.",
      "ls -l /etc/passwd\nid; groups\nsudo -l\nchmod 640 file; chown app:app file"),
    C("sec-linux", "Processes and job control", "ps, top, signals",
      "A process is a running program with PID, PPID, state, open FDs. Inspect with ps, top/htop; send signals with kill (TERM then KILL).",
      "Know foreground/background (&, fg, bg), nohup/systemd for long jobs, and that killing PID 1 in a container stops the container.",
      "Process: chương trình đang chạy với PID, PPID, state, FD. Xem bằng ps, top/htop; tín hiệu bằng kill (TERM rồi KILL).",
      "Biết foreground/background, nohup/systemd cho job dài; kill PID 1 trong container sẽ dừng container.",
      "kill -9 first skips graceful cleanup; prefer SIGTERM then escalate.",
      "ps aux | grep nginx\ntop\nkill -TERM <pid>; sleep 5; kill -KILL <pid>\npkill -f 'python worker.py'"),
    C("sec-linux", "systemd essentials", "Units, enable, journal",
      "systemd manages services via unit files. systemctl start/stop/restart/status/enable; journalctl reads logs.",
      "Know Type=simple vs forking, Restart= policies, and that failed units show in systemctl --failed.",
      "systemd quản lý service bằng unit file. systemctl start/stop/restart/status/enable; journalctl đọc log.",
      "Biết Type=simple vs forking, Restart=, và systemctl --failed.",
      "Editing unit files without daemon-reload is a classic mistake.",
      "systemctl status nginx\nsystemctl restart nginx\nsystemctl enable --now nginx\nsystemctl daemon-reload\njournalctl -u nginx -f --since '10 min ago'\nsystemctl --failed"),
    C("sec-linux", "Packages and software install", "apt/yum/dnf + caution",
      "Distro packages (apt/yum/dnf) give dependency resolution and updates. Pin versions in prod; prefer official repos or signed artifacts.",
      "For apps, prefer containers or versioned deploys over ad-hoc curl|bash to root.",
      "Gói distro (apt/yum/dnf) giải quyết dependency và cập nhật. Prod nên pin version; ưu tiên repo chính thức hoặc artifact đã ký.",
      "Với app, ưu tiên container hoặc deploy có version hơn curl|bash vào root.",
      "Mixing random PPAs/third-party repos without trust review is risky.",
      "apt update && apt install -y curl\nrpm -qa | grep nginx\ndnf list installed"),
    C("sec-linux", "Disk, filesystems, mounts", "df, du, mount",
      "Disk full is a top outage cause. df -h for filesystem free space; du -sh for directory usage; lsblk/mount for devices and mount points.",
      "Know inodes can exhaust before bytes (df -i). Clean logs, old images, and large /var carefully.",
      "Disk đầy là nguyên nhân outage phổ biến. df -h xem dung lượng; du -sh xem thư mục; lsblk/mount xem thiết bị.",
      "Inode có thể hết trước khi hết byte (df -i). Dọn log, image cũ, /var cẩn thận.",
      "Deleting open log files without restarting the writer may not free space until the process closes the FD.",
      "df -h; df -i\ndu -sh /* 2>/dev/null | sort -h\nlsblk\nlsof | grep deleted"),
    C("sec-linux", "Logs and troubleshooting paths", "Where to look first",
      "Classic paths: /var/log/syslog or messages, /var/log/auth.log, app logs under /var/log/<app>, journalctl for systemd units, nginx/apache access/error logs.",
      "Method: reproduce, check recent changes, logs/metrics, isolate layer (disk/net/app), fix and prevent.",
      "Đường dẫn kinh điển: syslog/messages, auth.log, log app, journalctl, access/error của nginx/apache.",
      "Quy trình: reproduce, thay đổi gần đây, log/metrics, cô lập lớp (disk/net/app), fix và phòng ngừa.",
      "Only reading app stdout and ignoring system journal or reverse-proxy errors misses root causes.",
      "journalctl -xe\ntail -n 200 /var/log/nginx/error.log\ndmesg | tail"),
    C("sec-linux", "Networking on the host", "ss, curl, DNS",
      "On a host: ss/netstat for listening ports; ip a / ip r for addresses/routes; curl -v for HTTP; dig/nslookup for DNS; ping/traceroute carefully (ICMP may be blocked).",
      "Confirm process-to-port binding before blaming the app or firewall.",
      "Trên host: ss/netstat xem port listen; ip a/r xem địa chỉ/route; curl -v HTTP; dig DNS; ping/traceroute (ICMP có thể bị chặn).",
      "Xác nhận process gắn đúng port trước khi đổ lỗi app hoặc firewall.",
      "Port is open via ss but wrong bind address (127.0.0.1 vs 0.0.0.0) still fails remote clients.",
      "ss -lntp\nip a; ip r\ncurl -I https://example.com\ndig +short api.example.com"),
    C("sec-linux", "File ops and text tools", "Daily command muscle",
      "Core tools: ls, cp, mv, rm, find, grep/rg, sed/awk, tar/gzip, chmod/chown, ln -s, less/tail -f.",
      "Be fluent reading configs and searching logs under time pressure.",
      "Công cụ lõi: ls, cp, mv, rm, find, grep, sed/awk, tar/gzip, chmod/chown, ln -s, less/tail -f.",
      "Thành thạo đọc config và tìm trong log khi bị áp lực thời gian.",
      "rm -rf without checking path is career-limiting — practice dry-runs and backups.",
      "find /var/log -name '*.log' -mtime +7\ngrep -R \"ERROR\" -n /var/log/app\ntar -czf backup.tgz /etc/nginx\ntail -f /var/log/syslog"),
    C("sec-linux", "Cron vs timers", "Scheduled jobs",
      "cron runs scripts on a schedule (crontab -e). systemd timers are the modern alternative with better logging via journald.",
      "Always log cron output; silent failures are common. Prefer idempotent scripts.",
      "cron chạy script theo lịch. systemd timer là lựa chọn hiện đại, log tốt hơn qua journald.",
      "Luôn ghi log output cron; fail im lặng rất hay gặp. Script nên idempotent.",
      "cron PATH differs from interactive shell — use absolute paths.",
      "crontab -l\nsystemctl list-timers"),

    C("sec-os", "Process management (OS view)", "Kernel scheduling basics",
      "OS schedules processes/threads on CPUs. States include running, sleeping, zombie. Context switches have cost; too many runnable tasks cause latency.",
      "DevOps angle: high load average + CPU steal/wait hints saturation or noisy neighbors (VMs).",
      "OS lập lịch process/thread trên CPU. Trạng thái: running, sleeping, zombie. Context switch tốn kém; quá nhiều task runnable gây latency.",
      "Góc DevOps: load average cao + CPU steal/wait gợi ý bão hòa hoặc noisy neighbor (VM).",
      "Load average alone without CPU/IO wait breakdown is incomplete.",
      "uptime; vmstat 1 5\nps -eo pid,ppid,stat,cmd | head"),
    C("sec-os", "Threads and concurrency", "Shared memory vs processes",
      "Threads share address space inside a process; processes are more isolated. Concurrency is not the same as parallelism (overlap vs multi-core simultaneous execution).",
      "Race conditions and deadlocks appear in apps and sometimes in ops scripts mutating shared state. Prefer clear locking or single-writer patterns.",
      "Thread chia sẻ không gian nhớ trong process; process cô lập hơn. Concurrency không đồng nghĩa parallelism.",
      "Race/deadlock xuất hiện ở app và đôi khi script ops sửa shared state. Ưu tiên lock rõ hoặc single-writer.",
      "More threads always faster can worsen contention and context switching."),
    C("sec-os", "Sockets", "Endpoints for network I/O",
      "A socket is an endpoint for communication (TCP/UDP/UNIX). Servers bind+listen; clients connect. TIME_WAIT and backlog matter under load.",
      "DevOps: ss -lntp shows listening sockets; connection refused vs timeout points to different layers.",
      "Socket là đầu cuối giao tiếp (TCP/UDP/UNIX). Server bind+listen; client connect. TIME_WAIT và backlog quan trọng khi tải cao.",
      "DevOps: ss -lntp xem socket listen; connection refused vs timeout chỉ lớp khác nhau.",
      "Blaming DNS for connection refused is usually wrong — refused means reachable host, nothing listening.",
      "ss -s\nss -ant | head"),
    C("sec-os", "I/O models", "Blocking, non-blocking, async",
      "Blocking I/O waits on the syscall; non-blocking returns immediately; async/evented models multiplex many connections (epoll). Disk I/O wait shows in iostat/%iowait.",
      "Slow disk or saturated volume often looks like app hang. Check iowait, queue depth, and disk latency.",
      "I/O blocking chờ syscall; non-blocking trả về ngay; mô hình async/event (epoll) phục vụ nhiều kết nối. Disk wait thấy ở iostat/%iowait.",
      "Disk chậm thường giống app treo. Xem iowait, queue, latency đĩa.",
      "Scaling app replicas when the bottleneck is a single slow disk/volume wastes money.",
      "iostat -xz 1 3"),
    C("sec-os", "Virtualization", "VM vs container",
      "VMs virtualize hardware with a hypervisor (stronger isolation, heavier). Containers share the host kernel (lighter, denser) with namespaces/cgroups for isolation/limits.",
      "Both can run together (containers on VMs). Know noisy neighbor and why CPU/memory limits matter.",
      "VM ảo hóa phần cứng qua hypervisor (cô lập mạnh, nặng hơn). Container dùng chung kernel host (nhẹ hơn) với namespace/cgroup.",
      "Có thể chạy container trên VM. Hiểu noisy neighbor và vì sao cần limit CPU/RAM.",
      "Assuming containers are VMs is wrong — kernel CVEs can affect all containers on a host."),
    C("sec-os", "Memory management", "RAM, swap, OOM",
      "Processes get virtual memory; kernel pages to RAM/swap. Free memory includes cache. OOM killer may terminate processes when RAM is exhausted.",
      "Watch RSS vs cache; don't panic at low free if cache is reclaimable. Disable swap carefully on K8s nodes per platform guidance.",
      "Process có virtual memory; kernel phân trang ra RAM/swap. Free gồm cả cache. OOM killer có thể giết process khi hết RAM.",
      "Xem RSS vs cache; đừng hoảng vì low free nếu cache thu hồi được. Tắt swap trên node K8s theo hướng dẫn nền tảng.",
      "Reading only the free column without buff/cache misleads.",
      "free -h\nps aux --sort=-%mem | head\ndmesg | grep -i oom"),
    C("sec-os", "Filesystems", "Structure, journaling, mounts",
      "Filesystems organize data on block devices (ext4, xfs, etc.). Journaling improves crash consistency. Mount options and fstype affect performance/features.",
      "Know inode vs data space; read-only remounts for recovery; why backing up mounted DBs needs consistent snapshots or dump tools.",
      "Filesystem tổ chức dữ liệu trên block device (ext4, xfs...). Journaling giúp nhất quán khi crash. Tùy chọn mount ảnh hưởng hiệu năng.",
      "Biết inode vs dung lượng data; remount RO khi cứu hộ; backup DB đang mount cần snapshot nhất quán hoặc tool dump.",
      "Copying live database files while writes continue risks a corrupt backup.",
      "findmnt"),
    C("sec-os", "OS checklist for VNPT-style tests", "JD OS keywords packed",
      "Be ready to define and contrast: processes vs threads; concurrency vs parallelism; sockets; blocking vs non-blocking I/O; VM vs container virtualization; memory (RAM/swap/OOM); filesystems and mounts.",
      "Tie each concept to an ops symptom: high load, TIME_WAIT, iowait, OOM kills, disk full (bytes/inodes).",
      "Sẵn sàng định nghĩa/đối chiếu: process vs thread; concurrency vs parallelism; sockets; I/O blocking vs non-blocking; VM vs container; memory; filesystem/mount.",
      "Gắn mỗi khái niệm với triệu chứng ops: load cao, TIME_WAIT, iowait, OOM, disk đầy (byte/inode).",
      "Pure textbook answers with zero ops linkage score poorly."),

    C("sec-network", "OSI vs TCP/IP", "Layer mental model",
      "OSI has 7 layers; TCP/IP is the practical model (link/internet/transport/app). Troubleshooting: physical/link, IP/routing, TCP/UDP, app protocol.",
      "Name common mappings: Ethernet/L2, IP/L3, TCP-UDP/L4, HTTP/TLS/L7.",
      "OSI 7 lớp; TCP/IP là mô hình thực dụng. Troubleshoot: vật lý/link, IP/routing, TCP/UDP, giao thức ứng dụng.",
      "Ánh xạ thường gặp: Ethernet/L2, IP/L3, TCP-UDP/L4, HTTP/TLS/L7.",
      "Calling HTTP a Layer 4 protocol is incorrect."),
    C("sec-network", "IP, subnetting, DNS", "Reachability basics",
      "Hosts need IP + mask/gateway. Private ranges (RFC1918) need NAT to reach internet. DNS maps names to IPs (A/AAAA/CNAME); mis-DNS looks like random outages.",
      "Check /etc/resolv.conf, dig, and TTL when debugging works-on-my-machine.",
      "Host cần IP + mask/gateway. IP private cần NAT ra internet. DNS ánh xạ tên sang IP; DNS sai giống outage ngẫu nhiên.",
      "Khi debug xem resolv.conf, dig, TTL.",
      "Caching old DNS after cutover — flush or wait TTL.",
      "ip a; ip r\ndig api.example.com A +ttlunits\ngetent hosts api.example.com"),
    C("sec-network", "TCP vs UDP", "Reliability tradeoffs",
      "TCP: connection-oriented, reliable, ordered (HTTP, SSH). UDP: connectionless, low overhead (DNS, some metrics/VPN). Choose based on need for reliability vs latency.",
      "TCP handshake (SYN/SYN-ACK/ACK) and retransmission explain some timeouts under loss.",
      "TCP: hướng kết nối, tin cậy, có thứ tự. UDP: không kết nối, nhẹ. Chọn theo nhu cầu tin cậy vs latency.",
      "Bắt tay TCP và retransmission giải thích một số timeout khi mất gói.",
      "UDP is always faster so use it for APIs ignores needed TCP/TLS semantics."),
    C("sec-network", "HTTP/HTTPS and common ports", "App-layer ops",
      "HTTP methods/status codes matter for gateways and health checks. HTTPS = HTTP over TLS. Common ports: 22 SSH, 80/443 HTTP(S), 53 DNS, 3306 MySQL, 5432 Postgres, 6379 Redis, 8080 alternate HTTP.",
      "Health checks should match real readiness (not only TCP open).",
      "HTTP method/status quan trọng với gateway và health check. HTTPS = HTTP qua TLS. Port thường gặp: 22, 80/443, 53, 3306, 5432, 6379, 8080.",
      "Health check nên khớp readiness thật (không chỉ TCP open).",
      "200 from nginx default page while upstream app is down fools shallow checks.",
      "curl -I https://example.com\ncurl -s -o /dev/null -w '%{http_code}\\n' http://127.0.0.1:8080/healthz"),
    C("sec-network", "Firewall, NAT, load balancer", "Path of a packet",
      "Firewalls allow/deny by rule (host iptables/nftables/firewalld or cloud SG). NAT translates addresses. Load balancers distribute traffic (L4 vs L7) and often do SSL termination.",
      "Debug order: security group/firewall, LB health, target listen address, app.",
      "Firewall cho/chặn theo rule. NAT dịch địa chỉ. LB phân phối traffic (L4 vs L7), thường terminate SSL.",
      "Thứ tự debug: firewall/SG, health LB, địa chỉ listen của target, app.",
      "Opening a port on the LB but not on the host firewall (or vice versa) is a classic miss."),
    C("sec-network", "TLS certificates (ops view)", "Expiry and chains",
      "TLS authenticates servers (and sometimes clients) and encrypts traffic. Cert expiry is a classic outage. Know chain of trust and SNI.",
      "Monitor notAfter dates; automate renewals (ACM/Let's Encrypt) where allowed.",
      "TLS xác thực server (đôi khi client) và mã hóa. Hết hạn cert là outage kinh điển. Biết chain of trust và SNI.",
      "Monitor ngày hết hạn; tự động renew khi được phép.",
      "Renewing a cert but forgetting to reload nginx/apache leaves the old cert live.",
      "echo | openssl s_client -servername example.com -connect example.com:443 2>/dev/null | openssl x509 -noout -dates"),
    C("sec-network", "Latency, loss, traceroute thinking", "Perf symptoms",
      "High latency vs packet loss vs DNS delay need different fixes. traceroute/mtr show path hops (may be incomplete). Measure from client and server sides.",
      "For apps: distinguish network RTT from app time-to-first-byte.",
      "Latency cao vs mất gói vs DNS chậm cần cách xử lý khác. traceroute/mtr cho thấy hop (có thể thiếu). Đo cả phía client và server.",
      "Với app: phân biệt RTT mạng và time-to-first-byte của app.",
      "Blaming the network without numbers (RTT, loss%, DNS time) is not engineering.",
      "mtr -rwzbc 20 example.com\ncurl -w 'dns=%{time_namelookup} connect=%{time_connect} ttfb=%{time_starttransfer}\\n' -o /dev/null -s https://example.com"),
]
